// AUTO-GENERATED by tools/symbols/gen_c_table.py 5210-v540
// DO NOT EDIT. Regenerate after refreshing tools/symbols/5210-v540.*.yaml.
//
// Sorted (addr, name) table for 5210-v540 (96 entries).
// Used by mad2's post-mortem caller-LR labeller (src/mad2/mad2.c) when
// the hand-coded label table doesn't match — falls back to nearest-symbol
// (binary-search-friendly because the array is addr-sorted).

#ifndef DCT3_SYMBOLS_5210_V540_H
#define DCT3_SYMBOLS_5210_V540_H

#include <stdint.h>

typedef struct {
    uint32_t    addr;     // flash address (Thumb bit stripped — match LR & ~1u)
    const char *name;     // semantic name (overlay > nokix; first wins on tie)
} Dct3Symbol;

static const Dct3Symbol dct3_symbols_5210_v540[] = {
    { 0x002001D0, "__CTYPE_PTR" },  // nokix
    { 0x002001FC, "MCU_VERSION_STRING" },  // nokix
    { 0x0020035E, "FREE" },  // nokix
    { 0x00237BD8, "GET_DATE_FORMAT" },  // nokix
    { 0x0026FD7E, "PHONE_TO_NAME" },  // nokix
    { 0x00286E32, "WIN_GET_PART_INFO" },  // nokix
    { 0x00286E72, "WIN_MARK_INFO_DIRTY" },  // nokix
    { 0x0028717C, "WIN_ALIGN_INFOS" },  // nokix
    { 0x0028739A, "WIN_PRINT" },  // nokix
    { 0x00287784, "UPDATE_SCREEN_SUB" },  // nokix
    { 0x00288F9A, "UPDATE_SCREEN" },  // nokix
    { 0x00293BD6, "DRAW_CHARS" },  // nokix
    { 0x00293C04, "PRINT_TEXT" },  // nokix
    { 0x00293D14, "DRAW_BOX" },  // nokix
    { 0x00294154, "DRAW_BITMAP" },  // nokix
    { 0x002946DC, "DRAW_PIXEL" },  // nokix
    { 0x002949F8, "DRAW_LINE" },  // nokix
    { 0x00294C6C, "GET_FONT" },  // nokix
    { 0x002AC4C4, "MENU_GET_ITEM" },  // nokix
    { 0x002AC50A, "MENU_DELETE" },  // nokix
    { 0x002AC54A, "MENU_REM_ITEM" },  // nokix
    { 0x002AD444, "MENU_OPEN" },  // nokix
    { 0x002AD614, "MENU_ADD_ITEM" },  // nokix
    { 0x002AE228, "OPEN_STATIC_MENU" },  // nokix
    { 0x002D8214, "DIALOG_CLOSE" },  // nokix
    { 0x002D827C, "DIALOG_OPEN_MSG" },  // nokix
    { 0x002D8452, "DIALOG_OPEN" },  // nokix
    { 0x002E9F6E, "PLAY_ANY_TONE" },  // nokix
    { 0x002ECD1A, "SEMAPHORE_OPEN" },  // nokix
    { 0x002ED3D0, "SEND_TASK_MESSAGE" },  // nokix
    { 0x002ED794, "TASKS_INIT" },  // nokix
    { 0x002EDBDC, "MALLOC_TRY" },  // nokix
    { 0x002EDC34, "EEPROM_READ_BYTES" },  // nokix
    { 0x002EDCB4, "MALLOC" },  // nokix
    { 0x002EF4DE, "SEMAPHORE_CLOSE" },  // nokix
    { 0x003078D0, "XBUS_CONNECT" },  // nokix
    { 0x00307BC0, "XBUS_GET_CONNECTION" },  // nokix
    { 0x00326EE8, "WCSNCMP" },  // nokix
    { 0x00327182, "WCSCMP" },  // nokix
    { 0x003271B8, "WCSSCAT" },  // nokix
    { 0x00337E80, "FTOA" },  // nokix
    { 0x00379B2C, "GET_TIMESTAMP" },  // nokix
    { 0x00396AB0, "NTOA2" },  // nokix
    { 0x00396D30, "ADD_TIME" },  // nokix
    { 0x00396DE0, "ADD_DATE" },  // nokix
    { 0x00396EEC, "ADD_DATETIME" },  // nokix
    { 0x003A7A60, "UPPER_REFRESH" },  // nokix
    { 0x003A7E48, "UPPER_MODE" },  // nokix
    { 0x003A7E78, "UPPER_REM" },  // nokix
    { 0x003A7EE8, "UPPER_SET" },  // nokix
    { 0x003ADE20, "DISPLAY_MSG" },  // nokix
    { 0x003BC272, "SET_LIGHTS" },  // nokix
    { 0x003BC842, "EEPROM_WRITE" },  // nokix
    { 0x003BC888, "EEPROM_READ" },  // nokix
    { 0x003C2CA0, "SEND_UI_MESSAGE" },  // nokix
    { 0x003D2FF6, "XBUS_SEND_FRAME" },  // nokix
    { 0x003D5ECE, "FIND_PPM" },  // nokix
    { 0x003D5EEC, "FIND_PPM_CHUNK" },  // nokix
    { 0x003D62CC, "STR2DOUBLE_EX" },  // nokix
    { 0x003D7BD0, "GENSIO_SET_COORD" },  // nokix
    { 0x003E22A4, "__SUBDF3" },  // nokix
    { 0x003E22AE, "__ADDDF3" },  // nokix
    { 0x003E56E2, "SET_ACTION" },  // nokix
    { 0x003E5F28, "__MULDF3" },  // nokix
    { 0x003E62CC, "EEPROM_WRITE_BYTES" },  // nokix
    { 0x003E6A28, "DELAY" },  // nokix
    { 0x003E70BC, "DIVMOD" },  // nokix
    { 0x003E7434, "__SUBSF3" },  // nokix
    { 0x003E743E, "__ADDSF3" },  // nokix
    { 0x003E7BF4, "UDIVMOD" },  // nokix
    { 0x003E88DC, "__MULSF3" },  // nokix
    { 0x003E8954, "DOUBLE_CMP" },  // nokix
    { 0x003E8C80, "SEND_LCD_DATA" },  // nokix
    { 0x003E8CC0, "GENSIO_END_TRANSACTION" },  // nokix
    { 0x003E96AC, "__TRUNCDFSF2" },  // nokix
    { 0x003E9740, "__FIXDFSI" },  // nokix
    { 0x003E9788, "FLOAT_CMP" },  // nokix
    { 0x003E97D0, "ATOI" },  // nokix
    { 0x003E99A4, "__FIXUNSDFSI" },  // nokix
    { 0x003E99E4, "__EXTENDSFDF2" },  // nokix
    { 0x003E9A5C, "__FLOATSISF" },  // nokix
    { 0x003E9B48, "__FIXSFSI" },  // nokix
    { 0x003E9DBC, "__FIXUNSSFSI" },  // nokix
    { 0x003E9E9C, "__FLOATSIDF" },  // nokix
    { 0x003E9EF4, "__FLOATUNSISF" },  // nokix
    { 0x003E9F94, "RAND" },  // nokix
    { 0x003E9FA8, "SRAND" },  // nokix
    { 0x003EA078, "__FLOATUNSIDF" },  // nokix
    { 0x003EA274, "TOUPPER" },  // nokix
    { 0x003EA29C, "TOLOWER" },  // nokix
    { 0x003EA2D0, "ISDIGIT" },  // nokix
    { 0x003EA320, "ATOF" },  // nokix
    { 0x003EA348, "RAM_INIT_DATA" },  // nokix
};
static const int dct3_symbols_5210_v540_n =
    (int)(sizeof(dct3_symbols_5210_v540) / sizeof(dct3_symbols_5210_v540[0]));

// Find the symbol with the largest addr <= target. Returns the index, or -1
// if target is below the first entry. O(log N) binary search. The caller can
// compute (target - table[idx].addr) to surface the offset (e.g. "FOO + 12").
static inline int dct3_symbols_5210_v540_nearest(uint32_t target) {
    int lo = 0, hi = dct3_symbols_5210_v540_n - 1, best = -1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        if (dct3_symbols_5210_v540[mid].addr <= target) { best = mid; lo = mid + 1; }
        else hi = mid - 1;
    }
    return best;
}

#endif // DCT3_SYMBOLS_5210_V540_H
