// AUTO-GENERATED by tools/gen_ext_eeprom_blobs.py — DO NOT EDIT.
// Baked NokiX virgin external-I2C-EEPROM images, auto-selected per model
// (ModelProfile.i2c_eeprom_default / .i2c_eeprom_size). See ext_eeprom.c.
#ifndef DCT3_EXT_EEPROM_BLOBS_H
#define DCT3_EXT_EEPROM_BLOBS_H
#include <stdint.h>

extern const uint8_t EE_NSE1[];   // NokiX nse-1.bin
#define EE_NSE1_LEN 2048u
extern const uint8_t EE_NSE3[];   // NokiX nse-3.bin
#define EE_NSE3_LEN 8192u
extern const uint8_t EE_NSE6[];   // NokiX nse-6.bin
#define EE_NSE6_LEN 32768u
extern const uint8_t EE_NSE8[];   // NokiX nse-8.bin
#define EE_NSE8_LEN 16384u
extern const uint8_t EE_NSM1[];   // NokiX nsm-1.bin
#define EE_NSM1_LEN 16384u

#endif
