#!/usr/bin/env python3
"""
gen_c_table.py — emit a sorted (addr, name) array + lookup helper as C,
for inclusion in mad2 / shells that want to label addresses at runtime
(e.g. the post-mortem caller-LR label).

Reads <build>.nokix.yaml + <build>.overlay.yaml (merging — overlay wins),
filters to in-flash code addresses (no RAM, no constants, no msg IDs),
and writes:

    src/models/<model>/symbols_<model>_<ver>.h

The header is fully self-contained — no malloc, no parsing, no Rexx, no
YAML dep. mad2 falls back to nearest-symbol from this table when the
hand-coded LR-list doesn't match.

Usage:
    tools/symbols/gen_c_table.py 3310-v579
    tools/symbols/gen_c_table.py 3310-v579 --out path/to/symbols.h
"""

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
sys.path.insert(0, str(HERE))
from lookup import load  # noqa: E402


def gen(build_tag: str, out_path: Path):
    addrs, _, _ = load(build_tag)
    if not addrs:
        sys.exit(f"no addresses for {build_tag}")

    # Filter to code-region symbols only (no RAM, no <0x100000 constants).
    code = [
        (n, e["addr"], e["source"], e["role"])
        for n, e in addrs.items()
        if e["kind"] == "code" and e["addr"] >= 0x00200000 and e["addr"] < 0x00400000
    ]
    code.sort(key=lambda t: t[1])
    if not code:
        sys.exit(f"no in-flash code symbols for {build_tag}")

    model = build_tag.split("-")[0]
    ver = build_tag.split("-", 1)[1]
    macro = f"DCT3_SYMBOLS_{model}_{ver.upper()}_H"
    array_name = f"dct3_symbols_{model}_{ver}"

    lines = [
        f"// AUTO-GENERATED by tools/symbols/gen_c_table.py {build_tag}",
        f"// DO NOT EDIT. Regenerate after refreshing tools/symbols/{build_tag}.*.yaml.",
        "//",
        f"// Sorted (addr, name) table for {build_tag} ({len(code)} entries).",
        "// Used by mad2's post-mortem caller-LR labeller (src/mad2/mad2.c) when",
        "// the hand-coded label table doesn't match — falls back to nearest-symbol",
        "// (binary-search-friendly because the array is addr-sorted).",
        "",
        f"#ifndef {macro}",
        f"#define {macro}",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    uint32_t    addr;     // flash address (Thumb bit stripped — match LR & ~1u)",
        "    const char *name;     // semantic name (overlay > nokix; first wins on tie)",
        "} Dct3Symbol;",
        "",
        f"static const Dct3Symbol {array_name}[] = {{",
    ]

    # Deduplicate by address — overlay wins (loaded second, but `addrs` already
    # has overlay-overridden). Keep the FIRST name we see at each address so the
    # array is unique-address.
    seen_addr = set()
    for name, addr, src, role in code:
        if addr in seen_addr:
            continue
        seen_addr.add(addr)
        tag = src if src != "nokix-locate" else "nokix"
        comment = f"  // {tag}{(' — ' + role) if role else ''}"
        # C string can't have """ — strip quotes from role
        comment = comment.replace('"', '\\"')
        lines.append(f"    {{ 0x{addr:08X}, \"{name}\" }},{comment}")

    lines.append("};")
    lines.append(f"static const int {array_name}_n =")
    lines.append(f"    (int)(sizeof({array_name}) / sizeof({array_name}[0]));")
    lines.append("")
    lines.append("// Find the symbol with the largest addr <= target. Returns the index, or -1")
    lines.append("// if target is below the first entry. O(log N) binary search. The caller can")
    lines.append("// compute (target - table[idx].addr) to surface the offset (e.g. \"FOO + 12\").")
    lines.append(f"static inline int {array_name}_nearest(uint32_t target) {{")
    lines.append(f"    int lo = 0, hi = {array_name}_n - 1, best = -1;")
    lines.append("    while (lo <= hi) {")
    lines.append("        int mid = (lo + hi) >> 1;")
    lines.append(f"        if ({array_name}[mid].addr <= target) {{ best = mid; lo = mid + 1; }}")
    lines.append("        else hi = mid - 1;")
    lines.append("    }")
    lines.append("    return best;")
    lines.append("}")
    lines.append("")
    lines.append(f"#endif // {macro}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    print(f"[gen_c_table] wrote {out_path}  ({len(seen_addr)} unique addresses)", file=sys.stderr)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build", help="Build tag (e.g. 3310-v579)")
    ap.add_argument("--out", help="Output path (default: src/models/<model>/symbols_<build>.h)")
    args = ap.parse_args()

    model = args.build.split("-")[0]
    if args.out:
        out = Path(args.out)
    else:
        out = REPO / "src" / "models" / model / f"symbols_{args.build.replace('-', '_')}.h"
    gen(args.build, out)


if __name__ == "__main__":
    main()
