#!/usr/bin/env python3
"""
gen_symbols_txt.py — emit a plain-text symbol sidecar for disfw.

The sidecar is the format tools/disfw.c reads to annotate disassembly:

    # Generated by tools/symbols/gen_symbols_txt.py <build>
    # fw-id: <fnv1a32>
    [addresses]
    0x002EEBAE REBOOT_FN
    0x002EEB94 CCONT_RESET_WDT
    ...
    [messages]
    0x00E4 MSG_T4_MDI_FAULT
    0x0366 MSG_KEY_DOWN
    ...
    [reasons]
    0x68 REASON_SWDSP
    0x05 REASON_FATAL_CPU_EXCEPTION
    ...

Three sections, all same line format: `<hex_value> <NAME>`. Messages and
reasons are sub-categorised so disfw can apply them differently (messages
attach to register-immediates near task-send calls; reasons attach to r0
immediates near calls into REBOOT_FN). Addresses cover both code and RAM.

Usage:
    tools/symbols/gen_symbols_txt.py 3310-v579
    tools/symbols/gen_symbols_txt.py 3310-v579 --out path/to/file.txt
"""

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from lookup import load  # noqa: E402

# Names whose `id` field encodes a *reason byte* (passed as r0 to REBOOT_FN /
# REASON_SETTER) rather than a msg id. Split them out so disfw can attach
# them to the right operand context. Today this is just `REASON_*` prefix.
REASON_PREFIX = "REASON_"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build", help="Build tag (e.g. 3310-v579)")
    ap.add_argument("--out", help="Output path (default: tools/symbols/<build>.symbols.txt)")
    args = ap.parse_args()

    addrs, msgs, _ = load(args.build)
    if not addrs and not msgs:
        sys.exit(f"no symbols for {args.build}")

    # Pull fw-id from the .nokix.yaml header (overlay should agree).
    fw_id = ""
    for suffix in ("overlay", "nokix"):
        p = HERE / f"{args.build}.{suffix}.yaml"
        if not p.exists():
            continue
        for line in p.read_text().splitlines():
            if line.strip().startswith("id:"):
                fw_id = line.strip().split(":", 1)[1].strip()
                break
        if fw_id:
            break

    lines = [
        f"# Generated by tools/symbols/gen_symbols_txt.py {args.build}",
        f"# DO NOT EDIT — refresh after editing tools/symbols/{args.build}.*.yaml",
    ]
    if fw_id:
        lines.append(f"# fw-id: {fw_id}")
    lines.append("")

    # Overlay-wins-on-ADDRESS: when two names map to the SAME address and at
    # least one comes from the hand-curated overlay, suppress the auto-located
    # (nokix-locate) alias in the sidecar so disfw's binary-search banner lands
    # on the corrected overlay name. (lookup.py already wins on NAME conflicts;
    # this fixes the *address*-collision banner ambiguity — e.g. the stale NokiX
    # LOCATE names EEPROM_READ_BYTES / MALLOC_TRY shadowing BLOCKING_MALLOC /
    # HEAP_FREE.) The nokix.yaml stays untouched (it is auto-generated and would
    # re-add the LOCATE name on a firmware bump); we only filter the sidecar.
    overlaid_addrs = {
        e["addr"] for e in addrs.values()
        if e.get("source", "").startswith("overlay")
    }

    # Addresses — sorted by addr for stable diffs (also makes binary search
    # tractable in disfw if it ever wants it). Keep ALL — disfw filters
    # constants vs real addrs by value range itself.
    lines.append("[addresses]")
    for name, e in sorted(addrs.items(), key=lambda kv: kv[1]["addr"]):
        # Skip enum-like constants (< 0x10000) — they'd false-match too much in
        # disasm. They stay in the YAML for other tools; disfw doesn't need them.
        if e["addr"] < 0x10000:
            continue
        # Drop a nokix-located name when an overlay name owns the same address.
        if not e.get("source", "").startswith("overlay") and e["addr"] in overlaid_addrs:
            continue
        lines.append(f"0x{e['addr']:08X} {name}")

    # Messages — split into "msg id" vs "reason byte" by name prefix.
    msg_entries  = [(n, e) for n, e in msgs.items() if not n.startswith(REASON_PREFIX)]
    rsn_entries  = [(n, e) for n, e in msgs.items() if n.startswith(REASON_PREFIX)]

    lines.append("")
    lines.append("[messages]")
    for name, e in sorted(msg_entries, key=lambda kv: kv[1]["id"]):
        lines.append(f"0x{e['id']:04X} {name}")

    lines.append("")
    lines.append("[reasons]")
    for name, e in sorted(rsn_entries, key=lambda kv: kv[1]["id"]):
        lines.append(f"0x{e['id']:02X} {name}")

    out = Path(args.out) if args.out else HERE / f"{args.build}.symbols.txt"
    out.write_text("\n".join(lines) + "\n")
    print(f"[gen_symbols_txt] wrote {out}  "
          f"({sum(1 for n, e in addrs.items() if e['addr'] >= 0x10000)} addresses, "
          f"{len(msg_entries)} messages, {len(rsn_entries)} reasons)",
          file=sys.stderr)


if __name__ == "__main__":
    main()
