// AUTO-GENERATED by tools/symbols/gen_c_table.py 3410-v546
// DO NOT EDIT. Regenerate after refreshing tools/symbols/3410-v546.*.yaml.
//
// Sorted (addr, name) table for 3410-v546 (182 entries).
// Used by mad2's post-mortem caller-LR labeller (src/mad2/mad2.c) when
// the hand-coded label table doesn't match — falls back to nearest-symbol
// (binary-search-friendly because the array is addr-sorted).

#ifndef DCT3_SYMBOLS_3410_V546_H
#define DCT3_SYMBOLS_3410_V546_H

#include <stdint.h>

typedef struct {
    uint32_t    addr;     // flash address (Thumb bit stripped — match LR & ~1u)
    const char *name;     // semantic name (overlay > nokix; first wins on tie)
} Dct3Symbol;

static const Dct3Symbol dct3_symbols_3410_v546[] = {
    { 0x002001D0, "__CTYPE_PTR" },  // nokix
    { 0x002001FC, "MCU_VERSION_STRING" },  // nokix
    { 0x0021762C, "FREE" },  // nokix
    { 0x0021F3BC, "SELFTEST_RESULT_RESET" },  // overlay — dispatch tbl 0x4A3AA8 ~msg0x1E; ZEROES [0x12CBBA] + struct (writes 0 NOT 1, verified); also posts ready-code19 to aggregator; NEVER dispatched on 3410. NOT the non-zero producer [00:14]
    { 0x0021F3E0, "SELFTEST_REPORT_TASK" },  // overlay — self-test result-reporting task body; writes result bytes via field-addr tbl 0x21F78C on result msg-ids; NEVER RUNS [00:50]
    { 0x0021F600, "SELFTEST_REPORT_MSG_SWITCH" },  // overlay — msg-id switch in report task; switches 119A/119B/11F8/1F/2A/11FB; reads queue via 0x2F8ABC [00:50]
    { 0x0021F78C, "SELFTEST_FIELD_ADDR_TBL" },  // overlay — word table of RAM result-byte addrs by test-num; 11FAB8/122881/12CBB9 etc [00:50]
    { 0x00221FE8, "SUBSYS13_INIT" },  // overlay — subsystem-13 init; reports ready code 13 to aggregator (bl 0x293378 @0x222016); dispatched via tbl 0x4A3A60 desc 0x02602A0A; NEVER entered on 3410 = real stall (upstream of [0x12CBBA]) [00:19]
    { 0x0025CEB4, "MMI_READY_CKSUM_GATE" },  // overlay — readiness gate: cksum=~BYTESUM16(0x17FDD0,0x70)&0xFFFF; cmp vs stored u16 [0x17FE40]; EQ->ready path (0x25CEF4), NE->not-ready: [0x17FE46]=3,[0x17FAEB]=0,demote bit7 of [0x17FE3D]. RE 2026-06-03 [06:08]
    { 0x0025CEC0, "READINESS_SUBSTATE_WRITER" },  // overlay — writes [0x17FE46]=3 (not-ready) when HW-readiness probe 0x3A9AF0 returns -1 [05:55]
    { 0x00260A26, "CONTACT_SERVICE_GATE" },  // overlay — reads MMI_READY_FLAG bit7; clear -> renders CONTACT/SERVICE strings (0x260C30) [22:56]
    { 0x00264FD4, "GET_DATE_FORMAT" },  // nokix
    { 0x0026F560, "AORD_GET_NEXT_CHAR" },  // nokix
    { 0x00270E8A, "WIN_GET_PART_INFO" },  // nokix
    { 0x00270ED6, "WIN_MARK_INFO_DIRTY" },  // nokix
    { 0x00271230, "WIN_ALIGN_INFOS" },  // nokix
    { 0x0027144C, "WIN_PRINT" },  // nokix
    { 0x00271830, "UPDATE_SCREEN_SUB" },  // nokix
    { 0x0027346A, "UPDATE_SCREEN" },  // nokix
    { 0x00282DE8, "DRAW_BITMAP" },  // nokix
    { 0x002836EA, "GET_FONT" },  // nokix
    { 0x00283B6C, "PRINT_TEXT" },  // nokix
    { 0x00283CBC, "DRAW_PIXEL" },  // nokix
    { 0x00283D02, "DRAW_LINE" },  // nokix
    { 0x00283DCE, "DRAW_BOX" },  // nokix
    { 0x002871C8, "TASK14_STATE_FANOUT" },  // overlay — readiness state*88 dispatcher; state byte [0x121A3A], status tbl 0x121DD4 (resolves task14_state/status sigs) [12:38]
    { 0x00293378, "READINESS_AGGREGATOR" },  // overlay — event-driven readiness aggregator; r0=subsys code 11..20 sets [0x12E268+idx]=1; all 9 -> POST_READY (analog 3310 0x278670) [07:50]
    { 0x002953EE, "MENU_GET_ITEM" },  // nokix
    { 0x0029542A, "MENU_REM_ITEM" },  // nokix
    { 0x00295472, "MENU_DELETE" },  // nokix
    { 0x002967E8, "MENU_OPEN" },  // nokix
    { 0x00296A14, "MENU_ADD_ITEM" },  // nokix
    { 0x002976D8, "OPEN_STATIC_MENU" },  // nokix
    { 0x002A723A, "DIALOGEX_CLOSE" },  // nokix
    { 0x002A72B8, "DIALOGEX_OPEN_MSG" },  // nokix
    { 0x002A765A, "DIALOGEX_OPEN" },  // nokix
    { 0x002A766C, "DIALOGEX_ADJUST" },  // nokix
    { 0x002CDAEC, "LOCALMODE_MSG_DISPATCH" },  // overlay — walks test-cmd handler table 0x4A38D4 - never runs in normal boot [23:47]
    { 0x002CE3F8, "LOCALMODE_TEST_HANDLER" },  // overlay — second test-msg handler using table base 0x4A3934 [23:47]
    { 0x002DD2D0, "READINESS_FLAG_FN" },  // overlay — reads [0x11F9EB]/[0x12287B] subsystem-ready flags [23:37]
    { 0x002DEA24, "DIALOG_CLOSE" },  // nokix
    { 0x002DEA8C, "DIALOG_OPEN_MSG" },  // nokix
    { 0x002DEC54, "DIALOG_OPEN" },  // nokix
    { 0x002E2D02, "PLAY_ANY_TONE" },  // nokix
    { 0x002E484C, "KEYPAD_ISR" },  // overlay — stores raw code to 0x12EA85 [08:54]
    { 0x002EB338, "RDY_CHK6_ALWAYS1" },  // overlay — readiness chk6: stub, returns 1 (always ready) [23:33]
    { 0x002F8408, "SEMAPHORE_OPEN" },  // nokix
    { 0x002F8642, "SELFTEST_RUN_BY_NUM" },  // overlay — runs a self-test by number (r0=test#); #7 -> CCONT chip-ID 0x38899C [22:49]
    { 0x002F8948, "SCHED_QUEUE_POST2" },  // overlay — sibling queue-post r0=task r1=msg; task19 self-test queue never receives [00:50]
    { 0x002F8A0C, "SEND_TASK_MESSAGE" },  // nokix
    { 0x002F8ABC, "SELFTEST_QUEUE_READ" },  // overlay — scheduler queue-read for current dispatched task index at 0x112948+1 [00:50]
    { 0x002F8D94, "TASKS_INIT" },  // nokix
    { 0x002F8DFC, "MMI_TASK_SCHED_INIT" },  // overlay — builds 23-rec runtime CB pool + 3 parallel tables (0x4A39C4 static + 0x114778 runtime), stores tbl ptr [0x112958] [23:33]
    { 0x002F8F24, "SCHED_QUEUE_POST" },  // overlay — cooperative-scheduler enqueue r0=taskQidx r1=msgptr; ring 1134F0+idx*28 [00:50]
    { 0x002F9194, "MALLOC_TRY" },  // nokix
    { 0x002F9240, "MALLOC" },  // nokix
    { 0x002F924C, "EEPROM_READ_BYTES" },  // nokix
    { 0x00300264, "SIM_GATE_DISP49" },  // overlay — disp49 SIM-gate eval (analog 3310 0x29EAC0); reads CALL_STATUS, selects insert-SIM vs standby/bypass [07:27]
    { 0x0031AEC0, "OSE_SEND" },  // overlay — cross-task send choke: task tbl 0x4C24EC[curtask 0x112949], route via XBUS_SEND_FRAME 0x3E1E9A [09:26]
    { 0x0031B034, "OSE_SIG_ALLOC" },  // overlay — OSE signal alloc: 8-byte header + body(size r0+2); returns body ptr [09:26]
    { 0x0031B04C, "OSE_SIG_STAMP_SEND" },  // overlay — stamp OSE hdr (sender pid [0x12BAA4], prio 0x10, dest sub-id) then call OSE_SEND [09:26]
    { 0x00323294, "WCSNCMP" },  // nokix
    { 0x0032335C, "WCSPBRK" },  // nokix
    { 0x003235BE, "WCSCMP" },  // nokix
    { 0x003235D6, "WCSSCAT" },  // nokix
    { 0x0033C8EC, "FTOA" },  // nokix
    { 0x0033D9A8, "RDY_CHK3_THREE_INPUT" },  // overlay — AND of [0x12CBBA]!=0 AND fn0x2DD2D0!=0 AND [0x122883]!=0; returns 0 on 3410 (all three never written) -> the failing readiness gate [01:20]
    { 0x0033D9CE, "SELFTEST_STATUS_REQ" },  // overlay — builds msg 0x11A2 posts task 19 via 0x2F8948; NEVER FIRES no callers [00:50]
    { 0x0033F534, "UPPER_MODE" },  // nokix
    { 0x00348A20, "DSP_MSG_PUMP" },  // overlay — DSP message-pump analog of 3310 0x2BB430 - sets [0x12BA10]=1 at 0x348A4A gated on [0x100E4]==0 [06:30]
    { 0x00348A4A, "DSP_UPLOADED_SET" },  // overlay — writer mov r0,1 strb [0x12BA10] [06:30]
    { 0x003507CC, "WDP_UNITDATA_REQ_TX" },  // overlay — WDP outbound: assemble datagram descriptor {type, 6-byte dest addr @+24, payload
    { 0x00350D4A, "WDP_ADDR_PAYLOAD_SER" },  // overlay — serialize typed WDP address (0/0x10/0x11..) + payload into signal body [09:26]
    { 0x00351760, "WDP_TX_BUILD_SIGNAL" },  // overlay — build OSE signal from WDP datagram: alloc 0x31B034 + serialize 0x350D4A; r0=len r1=buf [09:26]
    { 0x0035A340, "READINESS_REEVAL_DEMOTE" },  // overlay — re-eval that masks bit7 of [0x17FE3D] down to 0x08 when substate!=ready [05:55]
    { 0x0035A348, "READINESS_DEMOTE" },  // overlay — clears MMI_READY_FLAG bit7 (flag&=0x7F) then re-evals via 0x3B3D94 + reset-reason [0x17FEB5]; does NOT re-set bit7 here [22:56]
    { 0x00361562, "SET_ALARM" },  // nokix
    { 0x00361618, "RDY_CHK2_SELFTEST" },  // overlay — readiness chk2: 0x3E560A reads [0x12ADB1] nibble + scans 5 records [0x12ADE0+20] for nonzero (self-test/hw result) [23:33]
    { 0x0036EC20, "UPPER_REFRESH" },  // nokix
    { 0x0036F2BC, "SEMAPHORE_CLOSE" },  // nokix
    { 0x0036F31C, "UPPER_SET" },  // nokix
    { 0x0036F3E6, "UPPER_BLINK" },  // nokix
    { 0x0037C234, "GET_TIMESTAMP" },  // nokix
    { 0x003874E2, "EEPROM_BLOCKS_VALIDATE" },  // overlay — reads 8 EEPROM blocks via DESC_TBL; all-0xFFFF(virgin) -> sets invalid flags (entry+0x38=1, [0x387 flags]|=2) [22:12]
    { 0x0038899C, "SELFTEST_CCONT_CHIPID" },  // overlay — boot self-test: CCONT reg3 chip-ID, wants (v&0xFC)==0xB0 else 0xFD [22:02]
    { 0x00388AD8, "SELFTEST_TBL_INIT" },  // overlay — inits self-test results table 0x17FAE0 to all-0xFF at boot [22:49]
    { 0x0038B620, "RDY_CHK5_FLAG_12DFB0" },  // overlay — readiness chk5: ready iff [0x12DFB0]==0 [23:33]
    { 0x0038B6FA, "RDY_CHK7_FLAG_12DFB2" },  // overlay — readiness chk7: ready iff [0x12DFB2]!=1 [23:33]
    { 0x0038C380, "UI_ITEM_PROP_LOOP" },  // overlay — settime Done-screen layout pass: for each objarray[i] dispatch selector 0x3242 (subkeys 0xC006/C01F/C020); objarray[0] dangling after overflow [17:11]
    { 0x00393FCC, "RDY_CHK4_SELFTEST_RESULT" },  // overlay — readiness chk4: 0x393F6C switch on [0x17FDBC] (SELFTEST_RESULT_TBL+0x2DC) state-machine; returns ready only for certain values [23:33]
    { 0x00393FEC, "SUBSYS_READY_REPORT" },  // overlay — ready-report shim: subsys id in r0 -> 0x3BEF46(r0=1,r1=id); 0x32 PASS reports id 7 [00:27]
    { 0x00394560, "ANALOG_SEND_0x4C" },  // overlay — task18 self-send msg 0x4C (gated on analog state byte==4); 0x4C never dispatched -> no 0x4D ack [05:55]
    { 0x0039E8CC, "WDP_DISP_MSG1A1A" },  // overlay — generic msg 0x1A1A; reads EEPROM byte 0x4E, trace 0xF0A5/0xF087 [09:15]
    { 0x0039E974, "WDP_DISP_MSG20A2" },  // overlay — generic control msg 0x20A2; stashes req ptr to [0x12E630] [09:15]
    { 0x0039FBB6, "SEND_UI_MESSAGE" },  // nokix
    { 0x0039FF9C, "SEND_MESSAGE" },  // overlay — MMI message poster (r0=msgid|argc-in-top2bits, r1=argv0); sig-located from 3310 0x2E8A1A pattern, exact-cal. Use for keypress-char injection: send_message(KEYPRESS_MSGID|0x4000, char) [19:46]
    { 0x003A2BF0, "LOCALMODE_SESSION_SETUP" },  // overlay — sets local-mode flags [0x12643C]/[0x12643D]=1 on test-session establish [23:47]
    { 0x003A96B8, "NTOA2" },  // nokix
    { 0x003A9920, "ADD_TIME" },  // nokix
    { 0x003A99D0, "ADD_DATE" },  // nokix
    { 0x003A9AD4, "ADD_DATETIME" },  // nokix
    { 0x003A9AF0, "BYTESUM16" },  // overlay — generic helper: r0=ptr r1=count -> returns (sum of count bytes)&0xFFFF in r0. NOT a checksum-vs-stored; pure 16-bit byte-sum. RE 2026-06-03 [06:08]
    { 0x003B39E0, "DSP_UPLOADED_GET" },  // overlay — accessor ldrb [0x12BA10] ret - analog of 3310 0x2E0B20 [06:30]
    { 0x003B3B9E, "SUBSYS_STARTER" },  // overlay — subsystem-starter analog of 3310 0x2E0B26 - reads [0x12BA10] bails to 0x3B3C16 if not 1 - emits msg 0x16 [06:30]
    { 0x003B3D00, "READINESS_REEVAL" },  // overlay — service-entry/readiness re-eval; calls READINESS_DEMOTE, writes [0x2000C]=0x0A (IRQ disable), stages reason 4; loop over subsystem checks [22:59]
    { 0x003B3D94, "READINESS_CHECK" },  // overlay — readiness check called by READINESS_DEMOTE; r0=0 gates the reset-reason branch [22:56]
    { 0x003B59E2, "BOOTSTAGE_DRAW_SEND_0x32" },  // overlay — boot-stage fn: DRAW_CHARS(0x6D11)+TASK_SEND(task=1,msg=0x32); 3410-only stage absent on 3310 [00:27]
    { 0x003B59F6, "SET_LIGHTS" },  // nokix
    { 0x003B5AFA, "BOOTSTAGE_0x32_NOTREADY" },  // overlay — not-ready branch from 0x32 gate; sibling 0x3B5AFC draws 0x6D12 + sends msg=0x33 (re-eval) [00:27]
    { 0x003BA468, "DISPLAY_MSG" },  // nokix
    { 0x003BA57A, "CLOSE_DISPLAY_MSG" },  // nokix
    { 0x003BA5C0, "CLOSE_DISPLAY_MSG_DMI" },  // nokix
    { 0x003CB500, "EEPROM_WRITE" },  // nokix
    { 0x003CB53C, "EEPROM_READ" },  // nokix
    { 0x003D5F76, "BOOTSTAGE_DRAW_SEND_0x17" },  // overlay — common boot-stage: DRAW_CHARS(0x7201)+TASK_SEND(task=1,msg=0x17); last stage shared with 3310 (0x2E70FE) [00:27]
    { 0x003D5F9E, "SELFTEST_VERDICT_CLASSIFIER" },  // overlay — task=1 bootstage classifier; reads selftest result, routes verdict 0/1/2/3/5 (5=not-ready) [00:59]
    { 0x003D6128, "POST_READY_COMPLETION" },  // overlay — fires when all 9 readiness flags set; TASK_SEND task=1 msg=21 (byte-identical to 3310 0x2E72B8) [00:09]
    { 0x003D6ECE, "INTSOCK_CONNECT" },  // overlay — sel 0x4652: connect(sockaddr) destIP@+8/+12/+16 port@+20 = scktnt_send seam (control only) [09:21]
    { 0x003D6F42, "INTSOCK_CLOSE" },  // overlay — sel 0x4653: disconnect/teardown [09:21]
    { 0x003D6F8A, "INTSOCK_INIT" },  // overlay — INTSocket sel 0x2004 ctor [09:18]
    { 0x003D6FB2, "INTSOCK_EVT" },  // overlay — sel 0x4651: bearer event handler, evt 0x1A=call-established → clears pending [obj+28]; synth this to fake CSD connect [09:21]
    { 0x003DE2D8, "SELFTEST_GROUP_DISPATCH" },  // overlay — master self-test group dispatcher; r4=enable bitmask (arg low byte), runs tests via 0x2F8642 by #; skipped tests stay 0xFF [22:49]
    { 0x003DEE1C, "KEYPAD_MATRIX_SCAN" },  // overlay — drives cols reads rows [08:54]
    { 0x003E1DF0, "RDY_CHK1_CALL_FFS" },  // overlay — readiness chk1: call-active(0x3D0D08 reads [0x121DDF/0x121DE0/0x129524]) AND FFS-idle(0x328DBC: [0x12DD0C+28]==0 && +36==0) [23:33]
    { 0x003E1E5C, "XBUS_ENABLE_DEVICE" },  // nokix
    { 0x003E1E9A, "XBUS_SEND_FRAME" },  // nokix
    { 0x003E28D4, "STR2DOUBLE_EX" },  // nokix
    { 0x003E4424, "FIND_PPM" },  // nokix
    { 0x003E4444, "FIND_PPM_CHUNK" },  // nokix
    { 0x003E496E, "KEYPAD_KEYCODE_LOOKUP" },  // overlay — indexes KEYMAP_NORM by row*5+col [08:54]
    { 0x003E56E0, "PLAY_TONE" },  // nokix
    { 0x003E5720, "STOP_TONE" },  // nokix
    { 0x003E7D0E, "GENSIO_SET_COORD" },  // nokix
    { 0x003E8060, "WDP_INIT_MSG2004" },  // overlay — INIT/reset: clears control block r4+194 len14, registers via 0x3EF982 [09:15]
    { 0x003E80AA, "WDP_DISP_MSG59A1" },  // overlay — WDP-specific msg 0x59A1 [09:15]
    { 0x003E8106, "WDP_DISP_MSG5905" },  // overlay — WDP-specific data msg 0x5905; processes payload at msg+2 (datapath candidate) [09:15]
    { 0x003EC524, "UDPSOCK_SETADDR" },  // overlay — sel 0x4652: set window/addr params into obj (+8,+12,+14,+16) [09:21]
    { 0x003EC538, "UDPSOCK_INIT" },  // overlay — sel 0x2004: UDPSocket ctor; registers route via 0x3EF982 [09:18]
    { 0x003EC560, "UDPSOCK_FLOWCTL" },  // overlay — credit accounting: 0x18 send=++[obj+12] vs window[obj+14]; 0x17 recv=--; selector 0x45FB code 0x7E [09:21]
    { 0x003EC5BA, "UDPSOCK_EVT" },  // overlay — sel 0x4651 CONTROL-plane: datagram evt 0x17=recv/0x18=send, 3-state on [obj+8], flow-credit via helper 0x3EC560; NO payload copy [09:21]
    { 0x003EC66C, "UDPSOCK_CLOSE" },  // overlay — sel 0x2006: UDPSocket dtor/close [09:18]
    { 0x003EDD8A, "SET_ACTION" },  // nokix
    { 0x003EF9A8, "SELECTOR_LOOKUP" },  // overlay — OO method-table lookup: walk node list at [obj], match selector key u16, return method ptr; spins forever if obj freed (settime UAF) [17:11]
    { 0x003EFA14, "SELECTOR_DISPATCH" },  // overlay — virtual dispatch: SELECTOR_LOOKUP then bx to resolved method (obj=r0, selector=r1) [17:11]
    { 0x003F0B48, "__SUBDF3" },  // nokix
    { 0x003F0B52, "__ADDDF3" },  // nokix
    { 0x003F1392, "EEPROM_BLK_SCAN" },  // overlay — EEPROM driver: scans 64KB blocks for the active-block magic [22:07]
    { 0x003F565C, "__MULDF3" },  // nokix
    { 0x003F5A0E, "EEPROM_WRITE_BYTES" },  // nokix
    { 0x003F6684, "DIVMOD" },  // nokix
    { 0x003F6AA8, "__SUBSF3" },  // nokix
    { 0x003F6AB2, "__ADDSF3" },  // nokix
    { 0x003F7274, "DELAY" },  // nokix
    { 0x003F7586, "MEMCPY" },  // overlay — word/byte memcpy(dst=r0,src=r1,len=r2); overflows in settime crash with len=0xFFFE [17:11]
    { 0x003F75CA, "EEPROM_REC_READ" },  // overlay — EEPROM driver: reads active-block record bytes (parser) [22:07]
    { 0x003F77E8, "UDIVMOD" },  // nokix
    { 0x003F85B0, "DOUBLE_CMP" },  // nokix
    { 0x003F8628, "__MULSF3" },  // nokix
    { 0x003F8870, "SEND_LCD_DATA" },  // nokix
    { 0x003F88AE, "GENSIO_END_TRANSACTION" },  // nokix
    { 0x003F8E7C, "EEPROM_INIT" },  // overlay — EEPROM driver init; early boot (0x20018A->0x3B3CD6->here) scans+reads active block [22:07]
    { 0x003F9364, "__TRUNCDFSF2" },  // nokix
    { 0x003F9440, "FLOAT_CMP" },  // nokix
    { 0x003F9488, "__FIXDFSI" },  // nokix
    { 0x003F95E4, "ATOI" },  // nokix
    { 0x003F97BA, "__FIXUNSDFSI" },  // nokix
    { 0x003F9878, "__FLOATSISF" },  // nokix
    { 0x003F98F0, "__EXTENDSFDF2" },  // nokix
    { 0x003F9A1A, "__FIXSFSI" },  // nokix
    { 0x003F9B90, "__FIXUNSSFSI" },  // nokix
    { 0x003F9D60, "__FLOATSIDF" },  // nokix
    { 0x003F9DDC, "__FLOATUNSISF" },  // nokix
    { 0x003F9EC0, "__FLOATUNSIDF" },  // nokix
    { 0x003FA1F4, "ISDIGIT" },  // nokix
    { 0x003FA228, "RAM_INIT_DATA" },  // nokix
};
static const int dct3_symbols_3410_v546_n =
    (int)(sizeof(dct3_symbols_3410_v546) / sizeof(dct3_symbols_3410_v546[0]));

// Find the symbol with the largest addr <= target. Returns the index, or -1
// if target is below the first entry. O(log N) binary search. The caller can
// compute (target - table[idx].addr) to surface the offset (e.g. "FOO + 12").
static inline int dct3_symbols_3410_v546_nearest(uint32_t target) {
    int lo = 0, hi = dct3_symbols_3410_v546_n - 1, best = -1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        if (dct3_symbols_3410_v546[mid].addr <= target) { best = mid; lo = mid + 1; }
        else hi = mid - 1;
    }
    return best;
}

#endif // DCT3_SYMBOLS_3410_V546_H
