// AUTO-GENERATED by tools/symbols/gen_c_table.py 3310-v579
// DO NOT EDIT. Regenerate after refreshing tools/symbols/3310-v579.*.yaml.
//
// Sorted (addr, name) table for 3310-v579 (439 entries).
// Used by mad2's post-mortem caller-LR labeller (src/mad2/mad2.c) when
// the hand-coded label table doesn't match — falls back to nearest-symbol
// (binary-search-friendly because the array is addr-sorted).

#ifndef DCT3_SYMBOLS_3310_V579_H
#define DCT3_SYMBOLS_3310_V579_H

#include <stdint.h>

typedef struct {
    uint32_t    addr;     // flash address (Thumb bit stripped — match LR & ~1u)
    const char *name;     // semantic name (overlay > nokix; first wins on tie)
} Dct3Symbol;

static const Dct3Symbol dct3_symbols_3310_v579[] = {
    { 0x002001D0, "__CTYPE_PTR" },  // nokix
    { 0x002001FC, "MCU_VERSION_STRING" },  // nokix
    { 0x0020D6C0, "GU2_L1_MEAS_REQ_FORMATTER" },  // overlay — L1->task14 measurement-request formatter: reads L1 chan-state [0x10E151] (->msg[+2]) and [0x10E160+2] (the -0x1F dispatch-ladder key); BAND SPLIT: ids 0xA2x route to RR(16) via GU2_RR_TASK16_SEND 0x2B0744, ids 0xA3x/0xA4x route to task-14 (0x299134 immediate / 0x2996B8 queued); payload [0x10E160+0x30] edge-consumed. NOT DSP-state [0x110440]; the 'never fires / DSP-silent' clause was a runtime artifact [DIS]
    { 0x00215766, "FREE" },  // nokix
    { 0x00215BE8, "GU2_SIM_EF_LEN_RESOLVER" },  // overlay — file-id -> length/handler resolver; indexes EF desc table 0x32CB10 [DIS][DATA]
    { 0x00216FCE, "GU2_SIM_EF_READ_SST" },  // overlay — per-EF read+SST-nibble extractor via 0x215766; stores service nibble -> 0x10A688/689/68A for 6F37/6F39/6F41 [DIS][XREF 3]
    { 0x0021C630, "GU2_SIMLOCK_ACCEPT_GATE" },  // overlay — SIM IMSI-acceptance gate: builds arg frame, calls evaluator 0x286F68; verdict==10 ->accepted(1), 16->2, 17->3, else 0. 5 callers in SIM EF-read region 0x21Cxxx/0x21Dxxx [DIS][XREF 5]
    { 0x0021CFA8, "GU2_SIM_EFREAD_RESULT_SM" },  // overlay — SIM EF-read result dispatcher: maps file status codes to next-action handlers; drives read chain [DIS]
    { 0x0021D610, "GU2_SIM_EFREAD_SEQUENCER" },  // overlay — SIM data-read master sequencer: clears latch 0x11FF74; phased EF read; each read -> dispatcher 0x21CFA8 [DIS]
    { 0x00223A78, "RESET_CLASSIFIER_RUNTIME" },  // overlay — runtime reset-cause reader (returns 107/101/persisted)
    { 0x00223C10, "NETMON_SETTINGS_RW" },  // overlay — eeprom-backed netmon settings/counters helper, fields 0x601-0x606, bridges reboot_reason [0x11FF94] to [0x11FDA0] [00:15]
    { 0x002240B4, "NETMON_FIELD_RESOLVE" },  // overlay — field-id to value: index NETMON_FIELD_TABLE id*8, type-dispatch read u8/s8/s16 or call getter, output to 0x10E3B0 [00:50]
    { 0x002254E8, "NETMON_DISPLAY_RENDER" },  // overlay — per-display renderer: reads idx NETMON_DISPLAY_INDEX, looks up NETMON_DISPLAY_TABLE, walks layout tokens, formats via NETMON_FIELD_RESOLVE [00:50]
    { 0x002275B4, "NETMON_SET_MODE" },  // overlay — set_netmonitor_mode NokiX-confirmed: modes 0xF0reset/0xF1off/0xF2field/0xF3dev, test# below 0xF0 selects a display [00:14]
    { 0x00227690, "NETMON_RESET_CLASSIFIER" },  // overlay — reads reason [0x11FDA0], scans table 0x311C34, routes 0x68+0x73 to SWDSP bucket, bumps D36 counters [0x11FDB8+] [00:15]
    { 0x0022919E, "TASK5_MSG_0x4C_ENABLE_IRQ" },  // overlay — TASK_5/task17 msg-0x4C case: programs [0x20024]|=1 [0x20020]|=1 then TASK_SEND task=1 msg=0x4D ack [05:55]
    { 0x0022A578, "TASK_17_CHARGE" },  // overlay — task 17 — charging state machine (recipient of broker-fault msg 0x44)
    { 0x0022E5C4, "GU2_L1_MEAS_TASK10_INIT" },  // overlay — task-10 init: seeds meas state [0x111878]=22, sets master gate [0x110FE0]=1; registers RTOS id 10 [DIS][XREF]
    { 0x0022E650, "GU2_L1_MEAS_TASK10_ENTRY" },  // overlay — RTOS slot-10 entry; L1/radio-measurement task. Consumes d2m RSSI(0x83)/ALL_RSSI(0x8B)/NBR_TIMING(0x88); dispatch loop 0x22E95C [DIS][XREF]
    { 0x0022E95C, "GU3_TASK10_CELLSEL_FSM_DISPATCH" },  // overlay — task-10 cell-selection FSM state dispatch: state var [struct+2] (ldrsh); if >28 -> 0x233530 else 29-arm jumptable; states 8->20->11 camp progression [DIS] [21:42]
    { 0x002321DA, "GU3_RR_CAMP_STATE11_HANDLER" },  // overlay — task-10 cell-sel FSM state-11 handler: on d2m 0x89 (msg id [+4]==0x1802, opcode [+0]==0x89) reads camp-status [0x110F96]; if in {0x50,0x51,0x52
    { 0x002327DA, "GU3_RR_SEARCH_DRIVER_SITE" },  // overlay — RR search-driver emit site: reads pending-cfg [r1+3]==1, calls carrier-search 0x289434, then bumps netmon counter [0x11FDB8+0]. jmacato (github.com/jmacato) 9.2/12.1 step10 net-search kick [DIS] [21:41]
    { 0x00232824, "SWDSP_E4_WDOG_INITARM" },  // overlay — INITIAL arm of slot-36 watchdog: SOFTTIMER_ARM(36,0x9CD) + [0x111862]=0. One of 3 slot-36 arm sites (this, SWDSP_STAGER 0x2D12A4, healthy-tick 0x2EDC5A); ZERO disarm sites for slot 36 anywhere => never cancelled [06:43]
    { 0x0023D34C, "GU3_MM_IDLE_CAMP_PREDICATE" },  // overlay — returns 1 iff no MM-specific-proc (0x2EC11A==0) AND MM state [0x110454] in {5,6,7,10
    { 0x0023D37C, "GU3_MM_IDLE_STATE_GUARD" },  // overlay — MM idle-state guard: struct 0x110424 [+11]==0 && [+12]==1 && state [+48] in {5,6,7,10
    { 0x0023D638, "GU2_MM_TASK_MAIN" },  // overlay — MM task (id 15) main loop: self-registers id15, state struct 0x110424, MM state [0x110454] dispatched 1/2/3/7/9/10 [DIS][3330v MM]
    { 0x00240F88, "BROKER_DSP_HEALTHY_FLAG_INIT_ZERO" },  // overlay — INIT path: strb r1(=0),[r0=#115,r4=0x11FEAC] => clears [0x11FF1F]=0 during broker-struct (re)init fn 0x240F24 (sets r8=#115/0x73, r4=0x11FEAC base); the ONLY clear-to-zero writer; called from TASK_2_LOC entry 0x2444DA [08:32]
    { 0x002411F8, "GU2_D2M_0x74_SUBDISPATCH_FULL" },  // overlay — task2 handler for d2m 0x74 local/security response (forwarded by 0x2C1948): full subtype [M+8] table {0x0A,0x0D,0x10,0x33,0x34,0x35,0x36,0xC8,0xD0
    { 0x0024131C, "GU2_D2M_74_SIML_SUBDISPATCH" },  // overlay — d2m 0x74 SIML sub-router (near 0x2411F8): keyed on msg[+5] vs consts around 0x6511; routes SIM-lock/security subtypes -> 0x287A68(verdict), 0x287BE8(record store/decode-load), 0x2879C4(MSID). Frame is the DSP/local-security d2m 0x74 response [DIS][XREF]
    { 0x00241430, "MBUS_CMD_DISPATCH_CORE" },  // overlay — type-0x40 service-command dispatch core; selects 1 of 4 descriptor tables (0x320C88/0x320D08/0x320D88/0x320E08) by category r0, indexes by cmd[r6+1]*64; msg-id 0x100..0x121 via 8-byte table @0x321058 [16:45]
    { 0x00241F50, "GU_DSP_BOOTDONE_HANDLER" },  // overlay — LOC(task2) d2m sub-handler: sets DSP-state 0x111390.b0, calls bootready + 0x2AE058 [DIS][XARM exact 8850 0x241970]
    { 0x00243CE8, "FBUS_F40" },  // overlay — service-message dispatcher on [msg+8]/r2 via jump table (r2-4/r2-0xB); NokiX fbus_f40 locator (reached via FBUS f40 AND internal task-2 msgs); reads readiness-gate [0x11FEAC+105]bit0; routes local-security class 0x64 (simlock mgmt: step-router 0x2440A0 + field-setters 0x2873BA/0x2873EC) AND DSP-ops opcodes (0x89/0x65/0x0B..); caller 0x2445A8. Reconciles former scratch GU_LOC_DSPOPS_DISPATCH + GU2_SIMLOCK_CMD_HANDLER (both were facets of this one dispatcher) [DIS][XREF][NokiX]
    { 0x002442B4, "TASK_2_DISPATCHER" },  // overlay — task 2's msg-dispatch sub (10-entry jump table at 0x2442E0; case-DA = WDT kick)
    { 0x00244464, "BROKER_DSP_HEALTHY_CHECK" },  // overlay — RE-02 corroborated (disfw 0x244464 + WATCH 0x244464 step 38.09M/57.48M/... r5=0x11FEAC r0=0x73 r4=0x6E). Task-2 broker supervisor per-kick check: ldrb [r5+0x73]=[0x11FF1F] DSP-healthy flag; flag!=0(healthy)->0x244472 counter[0x11FF1A]=0; flag==0(unhealthy)->0x24446C counter++; strb at 0x244474; 0x2444A0 cmp#15 -> >=15 falls to TASK2_REBOOT_REISSUE_SITE 0x2444C8 bl REBOOT_FN([0x11FF94]). [07:46]
    { 0x00244472, "BROKER_SUPERVISOR_COUNTER_INC" },  // overlay — increments [0x11FF1A] (PC writes r0; ~every 19.6M cyc); climbs 0->15 under DSPKA_REPLAY=2 then reason-0x6C @0x2444A0 cmp#15. Cleared by SOFT_WDT_SUPERVISOR 0x2C199C on healthy runs; clears=0 under replay-burst (09-02 Task2) [12:23]
    { 0x00244474, "BROKER_SUPERVISOR_COUNTER_STORE" },  // overlay — RE-02 corroborated (disfw 0x244474 strb [r4=0x6E,r5=0x11FEAC] + RAMWATCH 0x11FF1A 00->01 attributed PC=0x244472, one insn prior). The single store for both counter++ (unhealthy) and counter=0 (healthy) branches of BROKER_DSP_HEALTHY_CHECK. Steady-state: bumps 0->1 every ~19.4M steps then SOFT_WDT_SUPERVISOR(0x2C199C) clears 1->0; never reaches 15 in clean 250M run. [07:46]
    { 0x002444C8, "TASK2_REBOOT_REISSUE_SITE" },  // overlay — bl REBOOT_FN(r0=[reboot_reason]) — supervisor overflow path
    { 0x002444D8, "TASK_2_LOC" },  // overlay — task 2 — LOC_TASK (broker consumer; switch on msg[3] event high-byte; 3330 prio 0x0F)
    { 0x002445F4, "GU_FAULT_NOTE_DISPATCH" },  // overlay — reason-code->note-id map + CONTACT SERVICE display; incr fault ctr [0x111723], at ==6 shows reason19 [DIS][XARM exact NHM-5 0x240158]
    { 0x0024E09C, "GU2_M2D_FREQBAND_TLV_LOOKUP" },  // overlay — m2d 0x7F-TLV builder: band-key lookup in 0x32ACBC, if [+1]==2 emits {0x7F,rec[0],rec[1]
    { 0x0024EB26, "GU2_L1_MDI_PACKET_BUILDER" },  // overlay — m2d MDI wire-format packet builder into alloc buf[+6..]: Path A (0x02 CHANNEL_CONFIGURE) strh #6/strb #8 sublen/type 0x02/0xE0/chan-flag; Path B (0x1C measurement list) mov #28 type 0x1C; wraps in 8-byte envelope, TASK_SEND(14). The 2/6 are the RTOS subtype+length, not a msg id; 10+ callers (0x24EFD0..0x251094). [DIS byte-verified][OMEGA47 9.1 0x02]
    { 0x002575B0, "GET_DATE_FORMAT" },  // nokix
    { 0x00259E22, "WIN_GET_PART_INFO" },  // nokix
    { 0x00259E62, "WIN_MARK_INFO_DIRTY" },  // nokix
    { 0x0025A1C4, "WIN_ALIGN_INFOS" },  // nokix
    { 0x0025A3E6, "WIN_PRINT" },  // nokix
    { 0x0025A7D8, "UPDATE_SCREEN_SUB" },  // nokix
    { 0x0025C32E, "SCREEN_WALKER_WDT_KICK" },  // overlay — 2nd SOFT_WDT_SUPERVISOR caller (display/table 27-item walk) [09:37]
    { 0x0025C380, "UPDATE_SCREEN" },  // nokix
    { 0x0025D34C, "GU_SECCODE_LEVEL_GLYPH" },  // overlay — level enum 0x10B889 -> lock status glyph U/A/L/space; display-glyph builder, NOT the verdict node [DIS][XARM exact NHM-5 0x258EBC]
    { 0x0025D3CC, "GU_SECCODE_VERDICT_DRIVER" },  // overlay — seeds 0x10BA84=0x7FFFFFFF, reads rec 0x753-0x755, sentinel==erased -> UI 0x8226 blocked [DIS][XARM exact NHM-5 0x258F3C]
    { 0x0025DCCC, "GU_SECCODE_REC8_READER" },  // overlay — 8-record EEPROM reader base 0x74B idx=state-2 (2..9) param 0x7FF0 [DIS][XARM exact NHM-5 0x25983C]
    { 0x0025E15C, "GU_SECCODE_EEPROM_SM" },  // overlay — security-code/lock state-machine dispatch; reads sec EEPROM 0x74B-0x755, sentinel 0x7FFFFFFF; emits UI msgs [DIS][XARM exact NHM-5 0x259CCC]
    { 0x0025F37C, "GU_SECCODE_STATUS_QUERY" },  // overlay — reads RAM struct 0x10B888[+3] (sec level/state), adds 0x2C substruct, tail-calls 0x25D34C [DIS][XARM exact NHM-5 0x25AEEC]
    { 0x00264E14, "OPCODE_DISPATCHER" },  // overlay — 70-caller opcode dispatcher; jump-table 0xFB4..0xFCB → 10 subsystem-init fns → SUBSCRIBE_ENGINE [13:45]
    { 0x00265340, "SWDSP_E4_ARM_LOOP_STATE6" },  // overlay — state-6 arm loop: ldrh id from 0x32C3DC[(state*10+i)*2]; bl 0x298738(id) x9. 0xE4 = table entry @0x32C456 (row6 col1). r0=0xE4 arm captured @step 4953348 LR=0x265355 [10:08]
    { 0x00265588, "STATE_FANOUT" },  // overlay — task-14 sub-state dispatcher (per [0x10B1FC+i]); 18-state jump table [13:45]
    { 0x00267024, "TASK_RECV_LOOP" },  // overlay — generic recv loop used by task 14 (and similar) — blocks when mailbox empty [13:45]
    { 0x00267038, "SWDSP_E4_TASK14_STATE_DECODE" },  // overlay — recv loop decodes msg id 0xFCD..0x100B: state=(id-0xFCD)/9, state-6 completion id=0x1004 (col1=0xE4 watchdog cancel); drives STATE_FANOUT 0x267734 [11:00]
    { 0x00267054, "SWDSP_TASK14_MSG_DECODE" },  // overlay — task-14 recv-loop entry-id decode: for id 0xFCD..0x100B sets slot state + [+8]=[+0x50+col], HEAP_FREE, loops. The inject-crash / free-list narrative is a runtime injection-mechanism artifact, NOT firmware signalling. Task 14 = L1/radio transaction manager [DIS]
    { 0x00267700, "GU2_TASK14_L1RADIO_ENTRY" },  // overlay — RTOS slot-14 entry (self-registers id 14 via 0x278670); 8-slot L1/radio-DSP transaction manager (slot-state 0x10AE90, 88B records 0x10AED8 stride 0x58). NOT a SWDSP self-test state machine; the '8x fan-out all bail at state=0' was a runtime observation [DIS][XREF]
    { 0x00267710, "SWDSP_E4_STATE_BYTE_DRIVER" },  // overlay — writes task-14 state byte [0x10AE61]=0..7 then 0xFF (step 4.95M burst); state->6 @4953113 immediately precedes the 0xE4 arm @4953348 (2nd-surface arm corroboration) [10:08]
    { 0x0026A834, "NETMON_CELL_LIST_RENDER" },  // overlay — PDF D1/D3 renderer iterates NETMON_CELL_RECORDS serving plus neighbours 1-4 [00:35]
    { 0x0026A876, "NETMON_CELL_RECORD_FMT" },  // overlay — PDF D1/D2/D3 per-cell processor, record = NETMON_CELL_RECORDS + idx*52 [00:35]
    { 0x0026DFEE, "CREATE_WIN_HANDLER" },  // overlay — msg 0x4C3A (create-window) handler
    { 0x0026E7DC, "GU_SECCODE_MSG_HANDLER" },  // overlay — msg-handler arm: loads req struct [0x10F680] +3/+7/+11 -> drives GU_SECCODE_EEPROM_SM 0x25E15C [DIS][XREF sole caller]
    { 0x0027362E, "PHONE_TO_NAME" },  // nokix
    { 0x00278248, "SWDSP_DSPMSG_HANDLER" },  // overlay — builds 8B msg id 0xFAC strh->[buf] then TASK_SEND_TYPED(14,buf); one of ~30 internal SWDSP task-14 senders (ids 0xFA1..0x1016). Producer of the 0xFCD-range ids; NOT ring-injectable [06:36]
    { 0x00278670, "READINESS_AGGREGATOR" },  // overlay — 9-flag readiness aggregator at [0x11156C..+8]; 9th set triggers post-ready 0x2E72B8 [13:45]
    { 0x00278E50, "SUBSCRIBE_ENGINE" },  // overlay — subscribe engine — final hop into BROKER_REGISTER (0x2EAD12); 0 hits in dormant boot [13:45]
    { 0x0028129C, "PRINT_TEXT" },  // nokix
    { 0x0028137C, "DRAW_BOX" },  // nokix
    { 0x002817C0, "DRAW_PIXEL" },  // nokix
    { 0x0028184A, "DRAW_BITMAP" },  // nokix
    { 0x00281ECE, "UI_PROCESSOR" },  // nokix
    { 0x00281F28, "DRAW_LINE" },  // nokix
    { 0x00282204, "GET_FONT" },  // nokix
    { 0x00284758, "MENU_GET_ITEM" },  // nokix
    { 0x0028479E, "MENU_DELETE" },  // nokix
    { 0x002847DE, "MENU_REM_ITEM" },  // nokix
    { 0x002856BC, "MENU_OPEN" },  // nokix
    { 0x00285858, "MENU_ADD_ITEM" },  // nokix
    { 0x00285E5C, "UI_DIALOG" },  // nokix
    { 0x002862B4, "OPEN_STATIC_MENU" },  // nokix
    { 0x0028655A, "GU2_SIMLOCK_BCD_MATCH" },  // overlay — nibble-wise packed-BCD comparator (0xF nibble = wildcard/terminator); evaluator uses it to match SIM IMSI against record compare[0..7] mask [DIS]
    { 0x002869E6, "GU2_SIMLOCK_REC_SERIALIZE" },  // overlay — record reader/serializer: copies record[0..7] compare (memcpy 0x2F0244), enable[+8], [+20], [+12..15], status[+17] OUT into a caller struct; NOT a writer [DIS]
    { 0x00286F68, "GU2_SIMLOCK_EVAL" },  // overlay — SIM-lock evaluator: loads =0x10EB48 (r8), walks stride 24 cap 10 via cursor [0x10EB18+10]; clears [0x10EB18+5] on entry; enable[+8] bit tests, BCD-match via 0x28655A (0xF wildcard) vs compare[0..7], status[+17]; returns verdict r4 9=reject/continue, 10=accept, 16=restriction [DIS][DATA][XREF]
    { 0x002873BA, "GU2_SIMLOCK_SET_ENABLE" },  // overlay — runtime writer: RMW enable byte record[+8] (sets high nibble/type via orr), record indexed by edit cursor 0x111722 [DIS]
    { 0x002873EC, "GU2_SIMLOCK_SET_STATUS" },  // overlay — runtime writer: stores record[+20]=arg0 and record[+21]=arg1 (from param struct [r4+11]/[r4+12]); indexed by edit cursor 0x111722 [DIS]
    { 0x002874EC, "GU2_LOCALSEC_SEND_SEQ" },  // overlay — task2-driven m2d type-0x70 local/security send sequence: emits MSID sub0x13/FAID sub0x14/IMEI sub0x15/SIML sub0x16 to MDISND(3) subtype-2; called from task2 0x241034; clears SIML state [0x10EB1A] [DIS][XREF][OMEGA47 7]
    { 0x002875B6, "GU2_LOCALSEC_SIML16_BUILD" },  // overlay — SIML sub-id 0x16 builder: alloc30, [+0]=2 subtype,[+2]=0x1A len,[+3]=0x70 TYPE,[+4]=0x16 subid,[+5]=24 blocklen; reads 24B ENCRYPTED block from PMM/EEPROM offset 0x20 via 0x2EF2C4 into [+6]; TASK_SEND(3); echoed by d2m 0x74 subtype 0x35 [DIS byte-verified][OMEGA47 7 0x16 24B]
    { 0x002875F8, "FAID_SUM8" },  // overlay — 8-bit additive checksum (sum&0xFF over N bytes); used by setfaid + FAID validation [22:26]
    { 0x00287A68, "GU2_D2M_SIML36_VERDICT" },  // overlay — d2m 0x74 subtype 0x36 handler (from 0x2411F8 stub 0x24130A): reads DSP pass byte [M+10]; pass==0 -> stores 1 (unlocked/allowed) else 0 to verdict boolean [0x10EB18+0]; posts event #2 via 0x298DF6. pass=0 semantics CONFIRMED. Single-byte RAM write, NOT the 0x10EB48 table [DIS][OMEGA47 7 final-SIML pass=0]
    { 0x00287ABA, "SETFAID" },  // overlay — FAID write svc-cmd: validates 8-bit sum + 0x4F marker, writes 12B FAID to EEPROM[0x14]; universal NokiX sig [22:26]
    { 0x00287BE8, "GU2_D2M_SIML35_RECORD_STORE" },  // overlay — d2m 0x74 subtype 0x35 record-store handler (dispatched from 0x2411F8/0x24131C, keyed on msg[+5]): checksum-eor-fold validates DSP response vs [msg+60] (GATE only, no byte change), then VERBATIM-memcpys the decoded 24B record from msg+12 into 0x10EB48+cursor*24 (cursor=[0x10EB18+10]) via stock alignment-opt memcpy 0x2F0244 -- NO MCU transform; sets aux[cursor]+20=3, bumps cursor; self-clocks next 0x70/0x16 request (EEPROM off 0x20+idx*24 via PMM 0x2EF2C4, TASK_SEND 3), loop <=10 records. Faithful producer of the decoded table mdi_gsm.c fakes; pairs with builder 0x2875B6 [DIS byte-verified 0x287C84-C94][DATA][XREF 0x241314]
    { 0x00289434, "GU3_RR_CARRIER_SEARCH_EMIT" },  // overlay — RR cell-search subroutine: builds 0x56 via 0x2A70AC(->r7), gates on [0x110ACC] deref, sends via 0x2A70DA(3=MDISND). Callers 0x2327DA/0x232ED6 (RR search driver). Handoff: local-sec/SIM-accept -> first network search [DIS][XREF] [21:41]
    { 0x0028D8F8, "DIALOG_CLOSE" },  // nokix
    { 0x0028D964, "DIALOG_OPEN_MSG" },  // nokix
    { 0x0028DB38, "DIALOG_OPEN" },  // nokix
    { 0x0028DFA8, "UI_DIALOGEX" },  // nokix
    { 0x0028F1F6, "GU3_RR_REG_ALLOWED_HELPER" },  // overlay — net-select-mode/reg flag pair: (([0x10A67C]==0 && [0x10B20C]==1) || ([0x10A67C]!=0 && [0x10B20C]!=0)) -> 1 [DIS] [21:41]
    { 0x0028F244, "GU3_SIM_FPLMN_FORBIDDEN_CHECK" },  // overlay — PLMN-selection forbidden-list gate: 4x3-byte FPLMN memcmp @[0x10A5DC+72+n*4] vs candidate PLMN(r0) via 0x2EFEBC; r6=3 forbidden / 4-5 allowed; writes code to [0x2000C]. CORRECTS CANONICAL LOCI-stage mislabel at same addr [DIS][DATA] [21:41]
    { 0x0028F7D2, "GU3_SIM_HOME_PLMN_PACK" },  // overlay — packs home-PLMN MCC/MNC BCD from SIM content struct [0x10A5DC+37] into 3-byte packed PLMN (r4); gated on cache flag bit [0x10A5DC+2] [DIS][DATA] [21:41]
    { 0x00290500, "KEYPAD_RECV_PUMP" },  // overlay — TASK_1_KEYPAD inner recv pump; calls TASK_RECV_BLOCKING 0x2992D4; ret slot 0x290507 (H5 09-03) [20:13]
    { 0x00290730, "TASK_1_KEYPAD" },  // overlay — task 1 — DEV_IO (14-state device-I/O dispatcher: charger/keypad/control/DSP-reboot msg27 + MDIRCV poke msg 0x53); keypad is one slice, not the whole task (GU_DEVIO_TASK)
    { 0x00290D60, "ANALOG_INIT_FIRES_0x4C" },  // overlay — task17 one-time analog init (guard [0x11173C]); calls ANALOG_READY_SEND_0x4C; reached when readiness HW probe reports ready [05:55]
    { 0x0029483A, "PLAY_ANY_TONE" },  // nokix
    { 0x002987C6, "SWDSP_E4_SOFTTIMER_ARM_BY_ID" },  // overlay — soft-timer arm/cancel manager 0x298738: keyed by timer-id (==msg id at node+10); matches [node+10]==r5(id). Timeout from per-id config [0x104970+id*12+4]; the 0xE4 node is never re-armed/cancelled post-arm [10:08]
    { 0x002988D2, "SOFTTIMER_ARM_BY_SLOTID" },  // overlay — soft-timer ARM/re-arm primitive (r0=slot-idx, r1=delta); per-slot struct = per_task_pending_count+0xEC+idx*12; matcher cmp[node+10],slotid then delta-queue insert via 0x298814. Healthy 0xE4 branch calls (36,0x9CD); the named-but-misplaced 0x2987C6 is a fall-through block of the slot service, not this [06:43]
    { 0x00298A98, "READY_QUEUE_INSERT" },  // overlay — ready-queue priority insert ([node+12]=pri)
    { 0x00298ACC, "SOFTTIMER_FIRE_FREE" },  // overlay — expired soft-timer fire+free (unlink + heap free) [23:26]
    { 0x00298B20, "SOFTTIMER_WALK" },  // overlay — soft-timer list walker (FIQ4 handler 0x2E4426 + idle gate); ages/expires timers [23:26]
    { 0x00298B66, "SEMAPHORE_OPEN" },  // nokix
    { 0x00298C64, "INJECT_MECH_WILD_POP" },  // overlay — T14INJECT crash = INJECTION-MECHANISM ARTIFACT (CONFIRMED 2026-06-05): control inject to task 19 (INJTASK=19) crashes IDENTICALLY (WILD-PC 0xFFFFFFFE via pop{pc
    { 0x00298F68, "LED_TIMEOUT_WALKER" },  // overlay — soft-timer LIST walk — ages timeouts, turns backlight off
    { 0x00299134, "TASK_SEND_TYPED" },  // overlay — TASK_SEND(r0=task,r1=msg) sibling of TASK_SEND_PRIM 0x29921C; indexes mailbox_ring_table 0x105E90. SWDSP OPCODE_DISPATCHER sends to task12/14 via this [06:36]
    { 0x0029921C, "SEND_TASK_MESSAGE" },  // nokix
    { 0x002992D4, "GET_TASK_MESSAGE" },  // nokix
    { 0x00299510, "TASKS_INIT" },  // overlay — create the 24 tasks from TASKS_INIT_TABLE
    { 0x0029966C, "START_ENGINE" },  // overlay — RTOS bootstrap
    { 0x002997B0, "TASK_SEND_IRQ" },  // overlay — IRQ-context twin of TASK_SEND
    { 0x00299A36, "MALLOC_TRY" },  // nokix
    { 0x00299A84, "HEAP_ALLOC" },  // overlay — non-blocking heap alloc wrapper: r0=size, tail-calls HEAP_ALLOC_CORE 0x2E533E, increments HEAP_ACCT_STRUCT+8 by (blk&~1)+4, epilogue 0x299ABA r0=ptr. MALLOC 0x299AEC tail-calls here (06-03 DIAG-03) [19:05]
    { 0x00299AEC, "MALLOC" },  // nokix
    { 0x00299AF8, "EEPROM_READ_BYTES" },  // nokix
    { 0x00299B26, "MALLOC_FAIL_RETRY" },  // overlay — alloc-fail block-retry PC parks on memory semaphore then retries malloc_fail sig hook [00:56]
    { 0x0029C46E, "SEMAPHORE_CLOSE" },  // nokix
    { 0x0029C632, "GU3_MM_REG_STATE_BRIDGE" },  // overlay — reg-status reset/bridge: gated [0x110C2A]==0; clears [0x10B204+2/+3], sets [0x1118A8]=0xFF, mirrors [0x10B204+9]->[0x11FF80]; on ==1 clears reg sub-state cluster (0x110C13/0x110C36/0x110C06, sets 0x110BF6=1) [DIS] [21:41]
    { 0x0029D0F4, "TASK_19_BACKGROUND" },  // overlay — task 19 — busiest @ idle (~216 msg/boot — background/timer)
    { 0x002A2128, "GU3_NET_STRENGTH_TO_BARS" },  // overlay — RxLev->signal-bar converter: walks NET_TRIGCONV_TABLE 0x32D6D8 (8 signed-halfword thresholds 100,75,50,25...) to level 0-7, reads display byte 0x32D6D9[lvl*2]; input r0=measured RxLev, struct r4=0x10E718 [DIS][DATA][OMEGA47 9.3] [21:46]
    { 0x002A223C, "GU3_NET_STRENGTH_UPDATE" },  // overlay — network signal-strength update handler: reads raw RxLev [0x10E718+32/+40] /10, calls 0x2A2128 converter, on [0x10E718+0] change stores+flags publish of signal-bar event 0x610D [DIS][DATA] [21:46]
    { 0x002A4224, "LOC_SUBMSG_DISPATCH" },  // overlay — task-2 LOC sub-message dispatcher; routes on subtype [r5+3] (3/5/0x11/0x13/0x47/0x82/0x83); compares [0x11FF1F] vs 26/27 (0x1A/0x1B) state-machine; increments [0x11FF1F] at 0x2A429E; called from TASK_2_LOC 0x24454E when [0x11FF1F]!=0 [08:32]
    { 0x002A429E, "BROKER_DSP_HEALTHY_FLAG_SETTER" },  // overlay — sets [0x11FF1F]=[0x11FEAC+0x73] via ldrb [r1=0x11FF1F]+1 strb (state-machine advance, NOT bool); reached from TASK_2_LOC 0x2444D8 (holds r6=0x11FF1F) -> LOC_SUBMSG_DISPATCH 0x2A4224 (subtype [r5+3]); MDI group [r4+3]~0x47/0x82/0x83 routes via 0x244546 to 0x2A4224; precond prior val==26(0x1A), payload word [r5+10..11]<=0; supervisor 0x244464 treats nonzero=healthy. NOTE flag is a LOC/DSP state byte cycling 0->..->26->27; single inject may not flip 0->nonzero (multi-msg walk) - Plan02 to confirm by injection. CONFIDENCE MEDIUM. [08:32]
    { 0x002A45C8, "GU3_MM_LU_ATTEMPT_COUNTER" },  // overlay — LU attempt-counter SM: reads reg flag [0x11FF1F], clamps [0x1151C+16] to 5 (GSM 04.08 LU attempt max 4), compares [0x11FF20] attempt idx [DIS] [21:41]
    { 0x002A486C, "BROKER_DSP_HEALTHY_FLAG_SET" },  // overlay — LOC submessage handler tail: sets [0x11FF1F]=1 (DSP-healthy), [+0x72]=2, sends XBUS frame. Gated on LOC/network activity -> NEVER runs at no-SIM standby -> [0x11FF1F] stays 0 -> counter kept in check only by idle SOFT_WDT clear (H4 09-02) [13:45]
    { 0x002A6CF8, "GU2_UL_BLOCK_MDISND_1B" },  // overlay — uplink LAPDm SEND_BLOCK builder: alloc 32B, strb 0x1B[+3]=MDI SEND_BLOCK, memcpy 23B LAPDm from template 0x32E1E4, TASK_SEND(3=MDISND) [DIS][OMEGA47 9.1]
    { 0x002A70AC, "GU3_CARRIER_SEARCH_56_BUILD" },  // overlay — MDI 0x56 CARRIER_SEARCH_LIST builder: alloc 164B (0x299AF8), memset0, [+2]=160 ring-len, [+0]=2 RTOS-subtype, [+3]=0x56 MDI-type, 160B payload; paired send fn 0x2A70DA (bl 0x2EB2CC/0x2C2D3A finalize, TASK_SEND(3=MDISND)). jmacato (github.com/jmacato) 9.2 step1 [DIS][OMEGA47 9.2] [21:41]
    { 0x002A70DA, "GU3_CARRIER_SEARCH_SEND" },  // overlay — m2d finalize (0x2EB2CC/0x2C2D3A) + TASK_SEND(3=MDISND) for 0x56. Sole caller 0x289462 (BL scan). [DIS byte-verified][XREF 1] [21:51]
    { 0x002A9FF8, "WINDOW_MGR_FN" },  // overlay — window manager — sole framebuffer allocator
    { 0x002AC6E0, "TASK_8_SIM" },  // overlay — task 8 — NOT the SIM driver (SIM is tasks 20/21 SIMUPL/SIML2); role uncorroborated, candidate IRDA/other d2m-op consumer (target of GU_D2M_OP_ROUTE_TASK8 opcodes 0x8D/8E/95)
    { 0x002AC90E, "XBUS_CONNECT" },  // nokix
    { 0x002AC9DA, "GU_D2M_OP_ROUTE_TASK8" },  // overlay — route d2m opcode 0x8D/8E/95 to task8 via SEND_TASK_MESSAGE [DIS][XREF sole caller MDIRCV]
    { 0x002ACB8E, "XBUS_GET_CONNECTION" },  // nokix
    { 0x002AE058, "GU_DSP_READY_BROADCAST" },  // overlay — publishes msg 0x7D00, seeds DSP cfg 0x10FF5C/60 from flash 0x329308/0x3292DC [DIS][XARM exact 8850]
    { 0x002AF240, "SIM_RECOG_TIMEOUT_FIRES" },  // overlay — reads [0x11FD08] (FEATURE_DISPATCHER index, overloaded cell); implied link to the DSP-reset / msg-0xE4 path is REFUTED — 0xE4 is the DSP keep-alive soft-timer tick, unrelated to SIM recognition
    { 0x002B0744, "GU2_RR_TASK16_SEND" },  // overlay — thin wrapper: TASK_SEND(16=RR) via 0x29921C; formatter routes L1 ids 0xA29/0xA2B/0xA2C/0xA2F here (RR band) [DIS][XREF]
    { 0x002B3384, "GU3_NET_STATUS_RR_POPULATE" },  // overlay — RR-side populate of net-status struct 0x110F8C from record [0x11160C+8]; camp-status [+10]=src[48], reg-status [+11]=src[46]; 1 caller 0x2B349E [DIS][XREF] [21:52]
    { 0x002B934C, "FTOA" },  // nokix
    { 0x002BA304, "GU3_RR_NETWORK_AVAILABLE_GATE" },  // overlay — RR network-available/can-register gate: 1 iff [0x110C20]!=0 && 0x28F1F6()!=0 && [0x10B20E]!=0 [DIS] [21:41]
    { 0x002BAB36, "GU_DSP_MAILBOX_WRITE_HW" },  // overlay — m2d mailbox HW word write ch3 [0x100DC] busy-gated, kick 0x30000=4/0x20008=2; byte-identical 8850/7110 [DIS][XARM]
    { 0x002BAB9E, "FIQ0_TASKSEND4" },  // overlay — FIQ0 handler 0x2BAB82 tail: sets [0x2000A]bit, [0x20008]=1, TASK_SEND_IRQ(task=4,msg=4) UNCONDITIONALLY on every DSP MDIRCV doorbell. task-4 then BROKER_DECODEs the ring; empty ring => msg discarded (BROKER_DECODE_EMPTY_GUARD). So the doorbell is necessary but NOT sufficient - the ring must carry an entry. Content beyond group byte largely irrelevant (any non-0/non-0xE4 decode bumps counter) [07:16]
    { 0x002BABA4, "MDISND_ENQUEUE" },  // overlay — MCU-to-DSP request-queue writer: copies record {len [01:17]
    { 0x002BAC58, "MDIRCV_QUEUE_DEPTH" },  // overlay — d2m ring available count = [0x101C8] - [0x101CA] (mod 100); DSP advances HEAD 0x101C8, MCU advances TAIL 0x101CA. Pointer identities CORRECTED (were reversed head[0x101CA]-tail[0x101C8]). 0 => empty => caller GU_DSP_D2M_DRAIN returns 0. XARM [DIS][XARM]
    { 0x002BAC72, "MDIRCV_DEQUEUE" },  // overlay — reads d2m tail element at 0x10000 + [0x101CA]*2 (base is 0x10000, CORRECTED from 0x10100); frame LOW byte = opcode, HIGH byte = length (CORRECTED — was group=r7>>8); advances tail; NO phantom register 0x102CA. Allocs broker msg tag 0x18/2. XARM [DIS][XARM]
    { 0x002BAC9E, "MDIRCV_RING_ENTRY_READ" },  // overlay — ldrh r7,[r4] in MDIRCV_DEQUEUE 0x2BAC72; reads ring word [0x10100+tail*2]; web ka_replay=2 vs native ka_replay=0 ring content diverges (09-02 DIFFTRACE)
    { 0x002BACB8, "MDIRCV_BROKER_MSG_ALLOC" },  // overlay — 06-03 DIAG: per-MDIRCV-message broker-buffer alloc inside MDIRCV_DEQUEUE — bl BLOCKING_MALLOC(0x299AF8) r0=payload+5, ptr stored [r5] then filled type=0x18 sub=2. THE LEAKING ALLOC SITE for the 0xE4 deep-idle heap leak [19:05]
    { 0x002BACEC, "GU_DSP_D2M_DRAIN" },  // overlay — IRQ-masked HW d2m ring drain (calls ring-count 0x2BAC58, if >0 reads ring word 0x2BAC72); NOT a broker msg-id decoder. XARM exact 7110 [DIS][XARM]
    { 0x002BACF0, "BROKER_DECODE_EMPTY_GUARD" },  // overlay — BROKER_DECODE head: MDIRCV_QUEUE_DEPTH 0x2BAC58; if depth==0 -> returns 0 (no dequeue). ANSWERS dan-IRQ-hypothesis 2026-06-05: a bare FIQ0/IRQ (DSP doorbell w/ empty ring) does NOT feed the watchdog counter -> task-4 0x2EDC46 cmp r4,#0 beq loops back without bumping [0x111862]. Watchdog liveness REQUIRES an actual ring ENTRY (depth>0) per ~97M window, NOT just an interrupt. DSPINT 0x30000bit2 is MCU->DSP (outbound, irrelevant to inbound liveness) [07:16]
    { 0x002BAD68, "MDIRCV_HEAD_INIT_BOOT" },  // overlay — RE-03: MCU-side MDIRCV head [0x101CA] init/advance during BOOT upload handshake (head=(ptr-0x10000)/2). Companion 0x2BACD8. Last write mono=3.78M; NO post-boot DSP-driven MDIRCV head advance exists in clean run => no unsolicited DSP heartbeat is produced by emulated DSP (this is the gap Phase 2/3 fills). (MDILOG + disfw) [07:52]
    { 0x002BADC2, "GU3_DSP_HPI_BOOTSTRAP_UPLOADER" },  // overlay — DSP HPI bootstrap uploader: [0x10000]=0/[0x10002]=0xFFFF (step1), writes 5w header @0x100F6, MAD2 0x20002 bit0 run/hold, 115=0x73 ping-pong 0x100FE/0x10100, uploads flash 0x200040 stride-32 -> HPI 0x10200, reads status/ver -> mirror 0x11038C+10/+12 [DIS][XARM][OMEGA47] [21:44]
    { 0x002BAF20, "GU3_DSP_HPI_OFFSET_MAP_INIT" },  // overlay — shared-RAM offset-map + clear: loads offset consts 0x1C8/0x1CA(MDIRCV h/t) 0xA6(MDISND h) 0xE2 0xDE 0xE0 0xDA 0xDC 0xCC 0xE4, then zeroes HPI 0x10000 for 0x800 words (step1 RAM test/clear) [DIS][OMEGA47] [21:44]
    { 0x002BB0B4, "GU3_COBBA_PARAM_DISPATCH" },  // overlay — cobba/DSP init-param dispatcher (=COBBA_DISPATCH): busy-gate [0x100E0]==0 @0x2BB0CE, 54-way jump table, handlers RMW 18-word param block 0x100A8-0x100CB, commit -> cmd word [0x100E0]=1 + DSPIF [0x30000]=4 + [0x20008]=2 (step6) [DIS][XREF][OMEGA47][EMU] [21:44]
    { 0x002BB3D8, "MDISND_AUDIOPATH_ENABLE" },  // overlay — RE-03: MCU->DSP [0x100E0]=1 audio/COBBA path enable, gated cmp r4,#47 (0x2F) at 0x2BB3D0; also sets [0x30000]=4 + [0x20008]=2. EVENT-DRIVEN not periodic: post-boot fires only in bursts (mono 30.7-32.8M cluster + 71.4M cluster, gaps 0.0M..38.7M irregular) — NOT a steady keep-alive poll. One-direction write, no reply expected. (MDILOG over [0,106M] + disfw) [07:52]
    { 0x002BB430, "GU3_DSP_CODEBLOCK_UPLOAD_DRIVER" },  // overlay — codeblock upload driver (=DSP_MSG_PUMP): reads req 0x100E2, streams chunks from descriptor tbl [0x1103B0] via memcpy 0x2EFA04, writes 5w header 0x100F6, reply 0x100E4=0x0002(more)/0x0004(done), clears 0x100E2 on done, DSPIF [0x30000]=4; also services ND cmd 0x100DE(1->0x2DD790/2->0x2DD778) + short word 0x100DA. Invoked from DSP IRQ 0x2E6F1E [DIS][XREF][OMEGA47][EMU] [21:44]
    { 0x002BB6DC, "GU3_DSP_ASIC_ID_COPY" },  // overlay — ASIC-ID copy (step7): reads MAD2 [0x20000] -> [0x101E2] (observed 0x0040) [DIS][OMEGA47] [21:44]
    { 0x002BBCB8, "W_GET_STRING" },  // overlay — wide get_string variant
    { 0x002BBF00, "PPM_STRING_LOOKUP" },  // overlay — PPM string lookup (lang, id) — handles id<51 special, else id-51 in body table [15:18]
    { 0x002BBFAC, "GET_STRING" },  // overlay — get_string(id) -> nokstr ptr (v5.79 — NokiX locator misses)
    { 0x002BC04A, "WCSPBRK" },  // nokix
    { 0x002BC076, "WCSNCMP" },  // nokix
    { 0x002BC276, "WCSCMP" },  // nokix
    { 0x002BC294, "WCSSCAT" },  // nokix
    { 0x002BCEF0, "DSP_MAILBOX_HANDLER" },  // overlay — IRQ4 handler — DSP mailbox dispatch
    { 0x002C1774, "SIM_STATE_DRIVER" },  // overlay — enum-keyed broker-publish dispatcher (r0=enum, r1=payload; publishes id 0x641F via 0x2EC62A, switch on enum) [DIS auditor-verified]. The specific enum->SIM_INFO_X semantics are un-re-derived 3330 labels [3330v] — NOT promoted; PERIPH_* members are peripheral, not SIM. Campaign SIMUPL/SIML2 SIM tracks never routed through here
    { 0x002C1948, "GU2_D2M_LOCALSEC_TO_TASK2" },  // overlay — d2m 0x70-class (0x74 local-security) response -> task-2 forwarder: allocs [r5+2]+10 buffer (0x2C195E), copies via GENERIC memcpy 0x2F0244 (prior 'UI_PHONEBOOK' was a MISID of the memcpy), TASK_SEND to task-2 where FBUS_F40 0x243CE8 dispatches on class 0x64; touches DSP reboot-enable gate 0x2E0ED2. Prior PHONEBOOK_MSG_TO_TASK2 label REFUTED by SIMlock recon [DIS][XREF]
    { 0x002C1996, "RESET_WATCHDOGS" },  // nokix
    { 0x002C199C, "SOFT_WDT_COUNTER_CLEAR" },  // overlay — strb 0 -> [0x11FEAC+0x6E]=[0x11FF1A]; unconditional at SOFT_WDT_SUPERVISOR entry. Runs on healthy native (perpetual ka=0 AND DSPNOKEEPALIVE) every ~19.6M cyc; runs 0 times under DSPKA_REPLAY=2 = the 0x6C root (idle-clear starvation) (09-02 Task2) [12:23]
    { 0x002C342C, "BROKER_TRACE_PUBLISH" },  // overlay — (r0=trace_id,r1=byte)->BROKER_GATE 0x2EABC0/BROKER_DELIVER. Consumer of literal 0x1004 @0x2A76A0 = OUTBOUND trace id, NOT a task-14 send (disambiguates the two 0x1004 uses) [06:36]
    { 0x002C3690, "GU2_D2M_RSSI_RESULTS_0x83" },  // overlay — MDIRCV boot-table[0x83] RSSI_RESULTS consumer: gate [0x110FE0]==1; forwards to task 10 (SEND_TASK_MESSAGE) [DIS][OMEGA47 9.1/9.3]
    { 0x002C3BEC, "GU2_D2M_RECV_BLOCK_CONSUMER" },  // overlay — MDIRCV OP_80 RECEIVED_BLOCK consumer: [msg+4] logchan, 24-bit framenum [msg+7..9]->[0x110FB4], gate [0x110FE0]==1 [DIS][OMEGA47 9.1]
    { 0x002C3CB8, "TASK4_D2M_HANDLERS_NO_T14" },  // overlay — task-4 d2m group handlers (jumptable 0x2EDB48, ids 0x83-0x8F -> 0x2C3690/0x2C3C9C/0x2C3BEC/0x2C3CF0/0x2C3CFC/0x2C3D4C/0x2C3CD4/0x2C3FC4/0x2C3D20/0x2C3CB8/0x2C35CA) + catchall 0x2ED6A0 + 0x70-class 0x2C1948: 19 TASK_SEND_TYPED calls, ALL target tasks 3/10/11/13. ZERO to task-14/12, ZERO into SWDSP engine. No ring d2m kicks SWDSP (Q2=b) [06:43]
    { 0x002C3CFC, "GU2_D2M_NBR_TIMING_0x88" },  // overlay — MDIRCV boot-table[0x88] NEIGHBOUR_TIMING_OFFSET consumer: gate [0x110FE0]==1; forwards raw frame to task 10 [DIS][OMEGA47 9.1]
    { 0x002C3D4C, "GU2_D2M_CHAN_CHANGED_0x89" },  // overlay — MDIRCV boot-table[0x89] CHANNEL_CHANGED_CNF consumer: gate [0x110FE0]==1; request-flag echo vs [0x11161C+2], calls RR 0x2B33F6 [DIS][OMEGA47 9.2 step4]
    { 0x002C3F88, "GU2_D2M_BLOCK_REQUEST_86" },  // overlay — d2m 0x86 BLOCK_REQUEST handler: gate [0x110FE0]==1; switch [msg+4] logchan -> block class -> GU2_UL_BLOCK_MDISND_1B 0x2A6CF8 [DIS][OMEGA47 9.1]
    { 0x002C3FC4, "GU2_D2M_ALL_RSSI_0x8B" },  // overlay — MDIRCV boot-table[0x8B] ALL_RSSI_RESULTS consumer: gate [0x110FE0]==1; result bufs 0x110FDC/0x110FE4 [DIS][OMEGA47 9.3]
    { 0x002C8A60, "CLOCK_TICK_PUBLISHER" },  // overlay — clock-tick handler — fires every RTC-MIN; loads r0=0x46BC, bl 0x2E87C8 (publish time-changed) [13:45]
    { 0x002C8A6C, "GET_DATETIME" },  // overlay — display getter — calls GET_TIMESTAMP 0x2CB588, formats; 0 hits at idle unless minute-change consumer runs [13:45]
    { 0x002C9F6C, "TASK_6_TONE" },  // overlay — task 6 — TONE_TASK (3330 prio 0x38); NOT the window compositor (older speculation refuted)
    { 0x002CB588, "GET_TIMESTAMP" },  // overlay — time-fn — checks clock-valid [0x111497]==0x2A; if valid → time-of-day; else → const 0x7FFFFFFF (drives deterministic RNG) [13:46]
    { 0x002CB622, "CONSUME_ROUTING_BYTE" },  // overlay — gate on [0x11149A] bit 5 (=0x20 set at boot); pass-through path to CLOCK_TICK_PUBLISHER [13:45]
    { 0x002CEF5C, "GU_SIM_HWWIN_WRITE" },  // overlay — write 8B cmd block to API-RAM/MAD window 0x3F0020+(ch<<13); byte0=0xFE opcode [DIS][XARM exact 8850]
    { 0x002CF0A2, "GU_SIML2_PRODUCER" },  // overlay — builds type2 descriptor, PUSHes ring op1, task_send(21,msg2) to SIML2 [DIS][XREF]
    { 0x002CF1F4, "GU_SIM_HWWIN_READ" },  // overlay — read 8B block from hw window (via 0x2D6184) into buffer, SIML2 reg RMW [DIS][XARM exact 8850]
    { 0x002D11F4, "SWDSP_STAGER" },  // overlay — DSP keep-alive fault→reboot escalation (GU_DSP_FAULT_REBOOT); 6-gate chain (EEPROM 0x607, reset-phase [0x1116B1], enable [0x11181C], inhibit [0x11FF9C], [0x11FFB0]&0xF, [0x111390]bit0); reason 0x68/0x69/0x73 for r0=1/2/3; calls REASON_SETTER + RESET_POSTER. Exactly two callers: MDIRCV 0x2EDB0E (r0=1→0x68), MDISND 0x2EA172 (r0=3→0x73). XARM exact 0x2CC9A4
    { 0x002D1EBA, "SELFTEST_DIRECT_RESET" },  // overlay — self-test fault direct reset (writes [0x20001]=4)
    { 0x002D455E, "SIM_RESET" },  // overlay — SIM card reset (ATR re-deliver)
    { 0x002D460E, "SIM_TRANSMIT" },  // overlay — sim_transmit — push bytes to SIM TX | GU3-RE (Phase-III): T=0 APDU byte-TX engine over MAD2 0x36 data port + 0x3F queue-count [DIS][XREF]
    { 0x002D490E, "SIM_FIQ6_ISR" },  // overlay — FIQ6 — SIM UART RX/TX events | GU3-RE (Phase-III): SIMI-UART FIQ6 ISR dispatches MAD2 0x38 int bits -> bit6=RX(0x2D487C) / bit4=TXempty(0x2D46E4) [DIS][XREF 0x2E702E]
    { 0x002D49C8, "SIM_INIT" },  // overlay — SIM driver init
    { 0x002D4A06, "SIM_RECEIVE" },  // overlay — sim_receive — pull bytes from SIM RX FIFO
    { 0x002D4E10, "GU3_NET_STATUS_COMMIT" },  // overlay — commits DSP-staged serving-cell status record into net-status struct 0x110F8C; camp-status [0x110F96]=[0x110F8C+10]=record[1]; arg!=0 stages(alloc+copy), arg=0 flushes; RESOLVES camp-status writer OPEN [DIS][XREF 6: FSM 0x2324A2, 0x89-hdlr 0x2C3DCE, net-mod 0x2D4F64/50F6/5184/5234] [21:52]
    { 0x002D605E, "GU_SIO_WRITE_BYTES" },  // overlay — resource-locked serial write primitive to hw window, toggles [0x20033] bit0 [DIS][XARM 98% 8850]
    { 0x002D6184, "GU_SIO_READ_BYTES" },  // overlay — resource-locked serial read: indirect byte-fetch via [0x1114BC] fnptr, MSB-first shift [DIS][XARM exact 8850]
    { 0x002D62C2, "MMI_BLOCK_BITSCAN" },  // overlay — deep-idle 16-bit bit-scan over FLASH_BLOCKS-table mask [0x10D4F8+idx*24+36]; the LCD-stall/idle web deep-idle wedge spinner (H5 09-03) [20:13]
    { 0x002D7146, "CHARGE_HEARTBEAT_HELPER" },  // overlay — charge-task idle assert(0x5B0F) — heartbeat ~1s — NOT SIM
    { 0x002D724C, "BROKER_FAULT_NOTIFIER" },  // overlay — send task 17 msg 0x44 + assert_log(0x5B06)
    { 0x002D7346, "ANALOG_READY_SEND_0x4C" },  // overlay — task17 self-send msg 0x4C -> TASK_5 ASIC-IRQ-enable handshake (mutex18; TASK_SEND task=17 msg=0x4C) [05:55]
    { 0x002D75C4, "SIM_FDN_INIT_OK_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=10) wrapper; log=0x5039 event=0x5400 [3330v label-only]
    { 0x002D75F2, "PERIPH_USE_MODE_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=2) wrapper — peripheral use-mode publish (NOT SIM); log=0x5029 event=0x53B0. use-mode semantics un-re-derived [3330v label-only]
    { 0x002D761E, "PERIPH_HOOK_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=4) wrapper — hook publish (NOT SIM); log=0x502C event=0x53B3 [3330v label-only]
    { 0x002D764A, "PERIPH_HEADSET_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=5) wrapper — headset publish (NOT SIM); log=0x502B event=0x53B2 [3330v label-only]
    { 0x002D7676, "PERIPH_CHARGER_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=6) wrapper — charger publish (NOT SIM); log=0x502A event=0x53B1 [3330v label-only]
    { 0x002D76A2, "PERIPH_IGN_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=3) wrapper — ignition publish (NOT SIM); log=0x5031 event=0x53F8 [3330v label-only]
    { 0x002D76EA, "PERIPH_ENUM7_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=7) wrapper — peripheral publish (NOT SIM); log=0x5032 event=0x53F9 [3330v label-only]
    { 0x002D7752, "SIM_INFO_STATUS_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=16) wrapper; log=0x502E event=0x53B5. payload status semantics un-re-derived [3330v label-only]. (Phase-II re-derives this addr as GU2_SIM_STATUS_PUBLISH — broker 0x502E + UI 0x53B5 pair)
    { 0x002D77CE, "SIM_UI_STATE_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=12) wrapper; log=0x503B event=0x5402. payload UI-state byte semantics un-re-derived [3330v label-only]
    { 0x002D780C, "SIM_INFO_PIN2_STATE_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=11) wrapper; log=0x503A event=0x5401. payload-indexed PIN2 state un-re-derived [3330v label-only]
    { 0x002D784C, "SIM_ENUM15_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=15) wrapper; log=0x502F event=0x53B7. enum->semantics un-re-derived [3330v label-only]
    { 0x002D78D4, "SIM_SCM_INIT_RESULT_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=8) wrapper; log=0x5036 event=0x53FD. enum->semantics un-re-derived [3330v label-only]
    { 0x002D7910, "SIM_SCM_INIT_OK_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=9) wrapper; log=0x5037 event=0x53FE [3330v label-only]
    { 0x002D7964, "SIM_UI_SUBSTATUS_PUBLISH" },  // overlay — SIM_STATE_DRIVER(enum=13) wrapper; log_block 0x5001+; twin 0x002D754A. sub-cycle semantics un-re-derived [3330v label-only]
    { 0x002D8654, "NTOA2" },  // nokix
    { 0x002D88D4, "ADD_TIME" },  // nokix
    { 0x002D8984, "ADD_DATE" },  // nokix
    { 0x002D8A90, "ADD_DATETIME" },  // nokix
    { 0x002D8AB0, "BYTESUM_DATETIME" },  // overlay — bounded byte-checksum loop after ADD_DATETIME [00:17]
    { 0x002DA37C, "PN_ROUTE_DISPATCH" },  // overlay — TASK_7/PN routing-table dispatcher: 8-byte-stride table @0x32B478 keyed by device-id [r5+6] (5 entries); bx handler @0x2DA386 or TASK_SEND @0x2DA392 (sender LR 0x2DA397). THE storm loop on web: forwards msg 0x6C54+0x7A14 to task 2 forever @>54.6M cyc; 0 hits on native [H4-SCHED-RE]
    { 0x002DA392, "PN_ROUTE_SEND_SITE" },  // overlay — the bl TASK_SEND inside PN_ROUTE_DISPATCH; storm dispatch site. WATCH=0 on native 25M steps; web 7000+/9M steps post-freeze [H4-SCHED-RE]
    { 0x002DA734, "TASK_7_PN" },  // overlay — task 7 — PN_TASK / Phone-Number (3330 prio 0x0C); hosts standby/idle UI; recv filter at 0x2DA738 checks [0x110550]==240
    { 0x002DA974, "PN_TASK" },  // overlay — Phonet protocol task — NokiX MBUS.rx anchor; mid-fn at first BL to BROKER_PUBLISH [02:07]  [task]
    { 0x002DB3AC, "UPPER_REFRESH" },  // nokix
    { 0x002DB784, "UPPER_MODE" },  // nokix
    { 0x002DB7B8, "UPPER_REM" },  // nokix
    { 0x002DB828, "UPPER_SET" },  // nokix
    { 0x002DDEFC, "DISPLAY_MSG" },  // nokix
    { 0x002DF5E6, "UI_HANDLER2" },  // nokix
    { 0x002E0D5C, "RESET_CLASSIFIER_BOOT" },  // overlay — boot-time reset-cause classifier (reads [0x20001])
    { 0x002E0E04, "TASK_0_IDLE" },  // overlay — task 0 — startup/idle (the running thread)
    { 0x002E0E32, "IDLE_LOOP_BACK" },  // overlay — TASK_0_IDLE loop-back target: bl SOFT_WDT_SUPERVISOR 0x2C1996; reached from boot fall-through 0x2E0E2A b AND back-edge 0x2E0EB2 beq (gate==0). Native ~22K steps; web frozen at 300 @~54.6M cyc [H4-SCHED-RE]
    { 0x002E0EA2, "IDLE_GATE_SET" },  // overlay — strb r9(=1) -> IDLE_WAIT_GATE [0x11186C]; TASK_0_IDLE arms the wait. On CURRENT build (post-H4-fix 50beb3b) the idle loopback re-runs SOFT_WDT_SUPERVISOR continuously on web (set-site freezes ~870 @100M but LOOP_BACK keeps climbing) -> no 0x6C (09.1-01) [21:50]
    { 0x002E0EAE, "IDLE_GATE_SPIN" },  // overlay — TASK_0_IDLE WFI-equivalent: ldrb gate / cmp #0 / beq IDLE_LOOP_BACK (gate==0) / b self (gate!=0). The idle wait. FIQ_DISPATCH_LOOP clears gate to release [H4-SCHED-RE]
    { 0x002E0ED2, "GU_DSP_REBOOT_ENABLE_GATE" },  // overlay — ldrb [0x11181C] reboot-enable gate !=0 [DIS][XREF 2D11F4]
    { 0x002E0ED8, "REASON_SETTER" },  // overlay — strb r0,[=reboot_reason]; bx lr — stages reset reason
    { 0x002E0F20, "RESET_POSTER" },  // overlay — post reset request (task 1 msg 0x1B + ch 28 msg 0x7D)
    { 0x002E3258, "SET_LIGHTS" },  // nokix
    { 0x002E33EC, "BATTERY_CHARGE_ANIM" },  // overlay — NokiX battery_charge sig; charging-anim frame counter [0x111701] cycles 0..4 (moving bars) [20:13]
    { 0x002E353E, "SERIAL_USART_TX_PUMP" },  // overlay — MBUS/FBUS accessory USART TX pump: writes next byte strb [0x2001A] @0x2E35C4, triggers via [0x20018]|=0x20; half-duplex turnaround w/ BUSY_DELAY; feeds PN_TASK(7) [12:00]
    { 0x002E35DC, "SERIAL_USART_RX_BYTE" },  // overlay — MBUS/FBUS accessory USART RX-byte handler: ldrb [0x2001A]=data -> [0x10BE6C]; sets [0x20019]|=7 [0x20018]|=0x40. Called by SERIAL_USART_RXDATA_FIQ [12:00]
    { 0x002E36B0, "MBUS_RX_DISPATCH" },  // overlay — MBus RX FIQ ISR posts task=7 msg=0x0003 (data received) -> FBUS/service handler task [23:48]
    { 0x002E36D2, "SERIAL_USART_RX_FRAME_SM" },  // overlay — accessory-USART RX frame state machine (state byte [0x10BE60], 0..7); acks IRQ [0x20008]=4; delivers frame to PN_TASK(7) via TASK_SEND_IRQ [12:00]
    { 0x002E3812, "SERIAL_USART_RESET" },  // overlay — USART mode/baud init: writes PUP_CONTROL [0x20015]; clears baud field bits[2:0] via &=0xF8 (=000=9600 per memory-map) then |=8; resets USART via [0x20018]=0x80 poll-bit7. Baud field NEVER set to 100(115200) anywhere in flash. Single caller 0x2E5958 [12:13]
    { 0x002E4034, "GU_EEPROM_WRITE_WRAP" },  // overlay — EEPROM write wrap; 260 callers [DIS][XARM exact NHM-5]
    { 0x002E4050, "EEPROM_WRITE" },  // nokix
    { 0x002E4076, "GU_EEPROM_READ_WRAP" },  // overlay — EEPROM read wrap (r1=logical id,r2=0x7FF0); 182 callers [DIS][XARM 97% NHM-5]
    { 0x002E4092, "EEPROM_READ" },  // nokix
    { 0x002E4112, "TIMER0_REARM" },  // overlay — Timer0 re-arm: t0_dest[0x20012]=current+interval(~0x19); drives the real FIQ4 tick [23:26]
    { 0x002E4116, "DISABLE_IRQ" },  // overlay — IRQ mask off; used by MBUS.rx hook installer [02:07]
    { 0x002E4130, "ENABLE_IRQ" },  // overlay — IRQ mask on; used by MBUS.rx hook installer [02:07]
    { 0x002E4248, "SOFTTIMER_DECREMENT" },  // overlay — soft-timer countdown decrement; elapsed=Timer0[0x20010]-snapshot[0x1115F8] [23:26]
    { 0x002E4278, "BOOT_FINALIZE_GATE" },  // overlay — boot finalize gate — waits ([0x20006]-[0x20004])>=30 sleep ticks (~0.9ms at 33055Hz, NOT 30ms as earlier comment said); posts init-complete on success → launches logo [19:48]
    { 0x002E4418, "FIQ5_TIMER1_HANDLER" },  // overlay — FIQ5/Timer1-overflow handler — drives soft-timer/LED-timeout walk
    { 0x002E4426, "FIQ4_TIMER0_HANDLER" },  // overlay — FIQ4 scheduler-tick handler; calls 0x298B20; acks [0x20008]=0x10 [23:26]
    { 0x002E4492, "UI_MENU" },  // nokix
    { 0x002E4710, "TASK_HANDLER_BX_R1" },  // overlay — alt dispatcher entry — bx r1 to handler(r0=msg), returns to 0x2E4714; per memory tag, also calls DEFERRED_TASK_DECODER on certain msgs [14:17]
    { 0x002E520C, "DEV_FREE_VENEER" },  // overlay — ARM device-free veneer; indexes per-task pool-base table flash 0x32E318 ([0x104845] sel); tail-reaches HEAP_FREE (H5 09-03) [20:13]
    { 0x002E52B0, "HEAP_FREELIST_INSERT" },  // overlay — sorted free-list insert; nodes {key@0,next@4
    { 0x002E52F6, "HEAP_FREELIST_REMOVE" },  // overlay — free-list remove (counterpart to insert) [23:26]
    { 0x002E533E, "HEAP_ALLOC_CORE" },  // overlay — underlying heap allocator returns NULL when no free block [00:56]
    { 0x002E5492, "HEAP_BLOCK_WALK" },  // overlay — heap free-list/block validate walk from base 0x1167C0; wedge-loop 0x2E54A2 grows as leaked blocks accumulate; coalesce target of HEAP_FREE [20:27]
    { 0x002E553C, "MEM_ALLOC" },  // overlay — best-fit aligned heap allocator (r0=align r1=size); free-list head [0x11182C]; epilogue 0x2E560E pops {r4-r7,pc
    { 0x002E5838, "PN_MBUS_SEND_FRAME" },  // overlay — firmware native MBus frame TX; reached via BL chain from PN_TASK per NokiX MBUS.rx; signature: NokiX-MBUS.rx-walk [02:07]
    { 0x002E5D96, "STANDBY_APP_DISPATCH" },  // overlay — standby app proc (table 0x324AFC)
    { 0x002E5EFE, "GU2_PHONE_STATE_EVENT" },  // overlay — system/phone-state event notify: r0=event id (0..35, gate 0x11FCE6), r1=param; 37 callers (SIM LOCI event 17) [DIS][XREF 37]
    { 0x002E6DD4, "FIQ8_CT_TIMER_HANDLER" },  // overlay — FIQ8 ct_timer 100Hz handler — increments [0x11139C] centisec
    { 0x002E6E8C, "SWDSP_DSPINT_PULSE_ONESHOT" },  // overlay — RE-03: MCU->DSP DSPINT [0x20002]|=2 pulse, IRQ-disabled wrap (0x2E4116/0x2E4130). ONE-SHOT at mono=13.1M only — not periodic. Not a keep-alive poll. (MDILOG + disfw) [07:52]
    { 0x002E6FBE, "FIQ_DISPATCH_LOOP" },  // overlay — FIQ dispatcher — reads [0x20008]&~[0x2000A], runs handlers
    { 0x002E6FC2, "IDLE_GATE_CLEAR" },  // overlay — mov r0,#0; strb r0->[0x11186C]; FIQ_DISPATCH_LOOP 0x2E6FBE first act on EVERY FIQ entry -> releases the idle spin. The native re-dispatch wake edge (09.1-01) [21:50]
    { 0x002E70A8, "BOOTSTAGE_DRAW_SEND_0x16" },  // overlay — boot-stage: DRAW_CHARS(0x7203)+TASK_SEND(task=1,msg=0x16); ready-path stage absent on 3410 [00:27]
    { 0x002E70FE, "BOOTSTAGE_DRAW_SEND_0x17" },  // overlay — common boot-stage: DRAW_CHARS(0x7201)+TASK_SEND(task=1,msg=0x17); 3410 twin 0x3D5F76 [00:27]
    { 0x002E729C, "BOOTSTAGE_DRAW_SEND_0x15" },  // overlay — boot-stage: DRAW_CHARS+TASK_SEND(task=1,msg=0x15); final ready advance; 3410 never sends 0x15 [00:27]
    { 0x002E72B8, "POST_READY_COMPLETION" },  // overlay — post-ready — sends msg 21 to task 1 (only); fan-out to tasks 5/6/17/19 happens downstream [13:45]
    { 0x002E82DA, "SIM_GATE_GREETING_LOAD" },  // overlay — ldrb r0,[0x11FCB8+r0] loads [0x11FD1B]; FIRST native-vs-web divergent read (09-02 DIFFTRACE; web bypass-poke=0x06 vs native=0x00)
    { 0x002E84B6, "UI_DISPATCHER" },  // nokix
    { 0x002E87C8, "EVENT_PUBLISH_HELPER" },  // overlay — build 16B event block, store event_id (r0<<16), dispatch via 0x2E8808 [13:45]
    { 0x002E8808, "SEND_UI_MESSAGE" },  // nokix
    { 0x002E884A, "GU_UI_MSG_MARSHAL" },  // overlay — UI msg marshal: parse [msg+0] id, count=id>>14, copy payload words to ctx 0x10F678+8/12/16, free msg [DIS][XREF sole caller 0x2E890C]
    { 0x002E8900, "TASK_5_UI" },  // overlay — task 5 — UI_TASK (3330 prio 0x78); large stack 0x1388; dispatcher 0x2E4492 reads [0x11FD08]
    { 0x002E8A1A, "GU_UI_MSG_POST" },  // overlay — engine-wide UI msg poster: push id+payload into internal ring 0x10F68C; 1288 callers incl 0x8226 FAID-blocked prompt [DIS][XREF]
    { 0x002E8DD0, "CCONT_BOTTOM_HALF_PUBLISHER" },  // overlay — task-1 bottom-half — read CCONT 0x0E pending, ACK, publish per-int 0x7901-0x7906 via 0x2EACDC [13:45]
    { 0x002E9332, "MMI_MSG_ROUTER" },  // overlay — MMI message router (v6.39 = 0x2E9896)
    { 0x002E98D4, "CCONT_BUS_WRITE_RMW" },  // overlay — CCONT/GenSIO serial-ctrl-bus RMW writer: cmd=[0x2002C] data=[0x2002D] status-poll [0x2006D]&3; table 0x32E88A maps logical reg->bus addr. NOT FBUS [12:00]
    { 0x002E99A4, "GU_ASIC_SERIAL_REG_READ" },  // overlay — ASIC serial-ctrl register READ companion; same bank tbl 0x32E878 shadow 0x1116C4 [DIS][XARM 91-99%]
    { 0x002E9A32, "IRQ2_CCONT_TOPHALF" },  // overlay — IRQ2 top-half — ack MAD latch + enqueue(task1, msg=0x51); runs every CCONT cascade incl RTC-MIN [13:45]
    { 0x002E9A52, "CCONT_RTC_INIT" },  // overlay — CCONT/RTC power-up init: direct [0x200AD]=0xCF [0x200AE]=0x20 [0x200ED]=0x20 [0x200EE]=0x80 then programs CCONT regs 0,1,3,5,6,7 via CCONT_BUS_WRITE_RMW + 5000-tick xtal delay. Debunks FBUS-init premise [12:00]
    { 0x002E9B80, "HW_RTC_READ" },  // overlay — reads CCONT day/hr/min/sec via remap table 0x32E878 (logical 0x09-0x0C -> phys 0x07-0x0A) → elapsed seconds [13:46]
    { 0x002E9DAC, "XBUS_ENABLE_DEVICE" },  // nokix
    { 0x002E9DEA, "XBUS_SEND_FRAME" },  // overlay — firmware native XBus frame TX; companion to PN_MBUS_SEND_FRAME [02:07]
    { 0x002E9E90, "MBUS_RX_DELIVER" },  // overlay — delivers assembled MBUS frame @0x10BE6C: mallocs copy (len+8/+6), TASK_SEND_IRQ to task 7 (PN_TASK) [16:45]
    { 0x002E9F6C, "TASK_3_MDI_SENDER" },  // overlay — task 3 — MDI_SENDER_TASK (dormant on boot; 3330 prio 0x0B match)
    { 0x002EA1B2, "FIND_PPM" },  // nokix
    { 0x002EA1D0, "FIND_PPM_CHUNK" },  // nokix
    { 0x002EA39C, "STR2DOUBLE_EX" },  // nokix
    { 0x002EA8A8, "DEFERRED_TASK_DECODER" },  // overlay — per-int decoder: msg-0x5DC=INT0 0x5DE=INT2 0x5E1=INT5 0x5E2=INT6 — gates clock advance [13:45]
    { 0x002EA914, "CLOCK_ADVANCE_HANDLER" },  // overlay — INT5/0x5E1 handler — gated on dialog [0x10E5F4] in {43,112,119
    { 0x002EABC0, "BROKER_GATE" },  // overlay — broker GATE — drops event unless [0x11FF28]!=0 AND subscription bitmap [0x11FF4C+(id>>11)] bit set
    { 0x002EABE8, "BROKER_DELIVER" },  // overlay — broker DELIVER — builds event block, sends to subscriber task's mailbox; 0 hits until [0x11FF28]=1
    { 0x002EACAA, "BROKER_ROUTER" },  // overlay — publish-side router: 0x2EACAA(0, event_id, 0) — calls BROKER_GATE then BROKER_DELIVER [13:45]
    { 0x002EACDC, "BROKER_PUBLISH" },  // overlay — thunk to BROKER_ROUTER — wraps publish call with (0, event_id, 0); analog of 3330 publish_wrapper@0x53ed4c [13:45]
    { 0x002EAD12, "BROKER_REGISTER" },  // overlay — subscribe register: [0x11FF28]=enable + memcpy 32B bitmap -> [0x11FF4C]; 4 callers in 0x243xxx all dormant [13:45]
    { 0x002EADC0, "GU_SIML2_RING_MGR" },  // overlay — SIM L2 8x24B ring 0x10FAAC: op1=PUSH@tail+193, op2=POP@head+192, count+194 [DIS][XARM exact 8850 0x304F28]
    { 0x002EAE44, "GU_SIML2_TASK" },  // overlay — task 21 — SIML2 SIM Layer-2 HW pump (inits ring 0x10FAAC, mode sel [0x10FAA8], 0xC350 timer, streams bytes to SIO); NOT an event broker. XARM exact 8850 0x304FAC [DIS][XARM]
    { 0x002EBD26, "FFS_RECORD_READ" },  // overlay — read FFS record by id (id r1, buf r2): find-by-id 0x2EBC3C + copy 0x2EBC64 [23:48]
    { 0x002EBDAE, "KEYBOARD_ENABLE" },  // nokix
    { 0x002EBFB2, "GENSIO_SET_COORD" },  // nokix
    { 0x002EC11A, "GU3_MM_SPECIFIC_PROC_ACTIVE" },  // overlay — MM specific-procedure/limited-service active helper: reads via 0x28FC5C, r0==1 && [sp+1]==1 -> 1 [DIS] [21:41]
    { 0x002EC3FA, "BROKER_CHANNEL_PUBLISH_DEAD" },  // overlay — DEAD/vestigial in v5.79: 0 BL callers + 0 pointer refs; sole consumer of 0x8F channel table 0x32C4E8 (which is ref'd ONLY by this fn's literal pool). The osmocom 0x8F-channel taxonomy (idx 0x18=MDISND etc) is NOT wired at runtime in this build. Live trace path = BROKER_ROUTER 0x2EACAA (41 leaf sites in 0x24xxxx, native event-ids cat 0x80/0x84) [16:52]
    { 0x002ED6A0, "MDI_BROKER_DELIVER_CATCHALL" },  // overlay — unrecognised-MDI-id catch-all -> BROKER_DELIVER -> PN_ROUTE_DISPATCH task-2 re-fan (the 0x6C storm path); reached for any MDI low byte not 0x8D/0x8E/handled (H4 09-02) [13:45]
    { 0x002ED702, "GU_MDI_M2D_WORD_TRACE" },  // overlay — above-line per-word m2d broker trace class 0x1800 (no DSP HW) [DIS][XREF sole caller MDISND]
    { 0x002ED776, "GU_MDI_PUBLISH_CORE" },  // overlay — MDI publish core: routes by 0x1800(m2d)/0x1900(d2m) prefix to 0x2EABE8 [DIS][XARM exact 8850]
    { 0x002ED7F4, "GU_M2D_PUBLISH" },  // overlay — m2d publish wrapper: id=0x1800|arg -> 0x2ED776 [DIS][XARM exact 8850]
    { 0x002ED802, "GU_D2M_REPUBLISH" },  // overlay — d2m republish wrapper: id=0x1900|arg -> 0x2ED776; sole caller 0x2EDB1E [DIS][XREF]
    { 0x002EDB04, "TASK_4_MDI_RECEIVER" },  // overlay — task 4 — MDI_RECEIVER_TASK (3330 prio 0x0A); in 3310 receives broker msg 0xE4 = MDI/DSP fault → stages SWDSP reset 0x68 (was mislabeled SIM-fatal)
    { 0x002EDB16, "MDI_ACTIVITY_COUNTER_INC" },  // overlay — ldrh r0,[r5,#2];add#1;strh -> bumps [0x111862] per non-0xE4 MDI msg to TASK_4. SOLE feed of the watchdog counter. MEASURED 2026-06-05: with default ka_replay=1 (39-record cap) counter hits 0 at the 203M tick -> 0x68. With DSPKA_REPLAY=0 (perpetual) counter=51 at both 106M+203M ticks -> NO 0x68 to 250M. The in-code dsp_default.c essay claiming silent/replay=1 is safe-to-2.8B is STALE/REFUTED [06:58]
    { 0x002EDB48, "GU2_MDIRCV_BOOT_DISPATCH_TABLE" },  // overlay — d2m BOOT jump table (op-0x83)<<2: 0x83->0x2C3690 0x84->0x2C3C9C 0x86->0x2C3F88 0x88->0x2C3CFC 0x89->0x2C3D4C 0x8B->0x2C3FC4; 0x80->0x2C3BEC 0x99->0x2C35CA [DATA][DIS]
    { 0x002EDC1E, "TASK4_BROKER_MSG_FREE" },  // overlay — 06-03 DIAG: TASK_4_MDI_RECEIVER frees the broker buffer here (bl HEAP_FREE 0x299A36, r0=r4=msg) on the NORMAL dispatch path. The 0xE4 path (gate 0x2EDC4C cmp#228 -> SWDSP_FAULT_DISPATCH 0x2EDC52) NEVER reaches here => the missing-free for the deep-idle leak [19:05]
    { 0x002EDC3C, "SWDSP_E4_REDISPATCH_GATE" },  // overlay — P02.1-01: task-4 loop gate. r6=1 => 0x2EDC3E bne 0x2EDC4C SKIPS BROKER_DECODE. At the FIRE (step105.94M) recv 0x2EDC36 returns r0=0xE4 DIRECTLY (soft-timer-posted msg), r6=1 => no decode, dispatch cmp#228. At BOOT (1.44M) recv returns task-msg 4, r6=0path => BROKER_DECODE drains MDIRCV ring. RECONCILES the two accounts: Phase1 saw the BOOT ring-drain; Phase2/the FIRE is the soft-timer re-issue. [09:51]
    { 0x002EDC40, "TASK4_BROKER_DECODE_CALL" },  // overlay — RE-01 corroborated (disfw 0x2EDC40 banner bl-caller of BROKER_DECODE + WATCH=0x2EDC4C step 105941998 r0=0xE4 r6=1 LR=0x298C49). Task-4 MDI_RECEIVER call site: on recv msg==4 (or r6 flag) calls BROKER_DECODE(0x2BACEC) which drains MDIRCV; r4=returned id; ==228(0xE4) => SWDSP fault dispatch at 0x2EDC52->0x2D11F4. [07:40]
    { 0x002EDC52, "SWDSP_FAULT_DISPATCH_RE03_VARIANT" },  // overlay — variant=A (DSP-initiated heartbeat). This is the 0xE4->SWDSP_STAGER(0x2D11F4) branch target in task-4. EVIDENCE (RE-03): MDILOG over [0,~106M] shows NO periodic MCU->DSP poll. MCU->DSP traffic = boot upload/self-test (<3.8M) + event-driven audio-enable bursts (0x2BB3D8 [100E0]=1, irregular gaps 0.0-38.7M) + one DSPINT pulse (0x2E6E8C @13.1M). SENDLOG: zero direct 0xE4 sends (corroborates). No steady-cadence request-reply => NOT variant B. Healthy flag [0x11FF1F] (Plan01: never written clean run) would be refreshed by UNSOLICITED DSP->MCU MDIRCV traffic the emulated DSP never emits => Variant A. SINGLE-MESSAGE in steady state (no multi-msg handshake observed). FIQ0-DELIVERABLE: yes (Variant A = write MDIRCV + raise FIQ0 per dsp_default.c self-test responder; IRQ4-free, respects post-boot-IRQ4 hazard). NOTE entry — Plan 01-03 owns promote. [07:52]
    { 0x002EDC5A, "SWDSP_E4_WDOG_REARM" },  // overlay — 0xE4 healthy branch: counter [0x111862]!=0 -> SOFTTIMER_ARM(slot36,0x9CD) re-arms watchdog window + strh 0 -> [0x111862] reset. UNCONDITIONAL re-arm => watchdog is PERPETUAL (View A) [06:43]
    { 0x002EDCB2, "GU3_SIGNAL_BAR_EVENT_POST" },  // overlay — posts display event id (0x610D signal-bar) via 0x2EDC70 to window/display task; r0=event id r1=data [DIS] [21:46]
    { 0x002EDD4A, "ASSERT_LOG" },  // overlay — generic assert_log(code:r0, data:r1) — broker pubsub publish
    { 0x002EE070, "GU3_DSP_CODEBLOCK_REQ_SITE" },  // overlay — site referencing HPI codeblock-request word 0x100E2 (jmacato (github.com/jmacato) 0x0E2 + IRQ4); DSP-side codeblock handshake MCU end - role TO-FIND track [DIS][OMEGA47 §6.2] [21:31]
    { 0x002EE5D0, "__SUBDF3" },  // nokix
    { 0x002EE5DA, "__ADDDF3" },  // nokix
    { 0x002EEB94, "DEV_RESET_WATCHDOGS" },  // nokix
    { 0x002EEBAE, "REBOOT_FN" },  // overlay — universal reboot fn (noreturn; r0=reason)
    { 0x002EEFEE, "SET_ACTION" },  // nokix
    { 0x002EF160, "__MULDF3" },  // nokix
    { 0x002EF294, "EEPROM_WRITE_BYTES" },  // nokix
    { 0x002EF2C4, "GU2_PMM_EEPROM_BLOCK_READ" },  // overlay — PMM/EEPROM block read(r0=offset/rec,r1=dst,r2=len): source of FAID(0x14 12B), IMEI(0x15), SIML(0x16 24B from off 0x20) local-security blocks [DIS][XREF FAID/IMEI/SIML builders]
    { 0x002EF3C8, "GENSIO_READ_HELPER" },  // overlay — GENSIO txn helper — start txn @0x2002D, poll status @0x2006D bit1, read data; called for ADC/CCONT-data reads; our 0x2D data path returns stale (only 0x6D status modeled as always-ready) [19:48]
    { 0x002EF544, "DIVMOD" },  // nokix
    { 0x002EF5F8, "__SUBSF3" },  // nokix
    { 0x002EF602, "__ADDSF3" },  // nokix
    { 0x002EF9E4, "DELAY" },  // nokix
    { 0x002EFA84, "UDIVMOD" },  // nokix
    { 0x002EFB1C, "SERIAL_USART_STATUS_FIQ" },  // overlay — FIQ handler (dispatch slot @0x2E7028) for accessory-USART status/error: reads [0x20019] bits5/6/7 + [0x20018] bit7; acks via [0x2000A]|=8 [12:00]
    { 0x002EFB7A, "SERIAL_USART_RXDATA_FIQ" },  // overlay — FIQ handler (dispatch slot @0x2E7022) for accessory-USART RX-data-ready; tail-calls SERIAL_USART_RX_BYTE 0x2E35DC [12:00]
    { 0x002EFF38, "DOUBLE_CMP" },  // nokix
    { 0x002EFFB0, "__MULSF3" },  // nokix
    { 0x002F0184, "DRAW_CHARS" },  // nokix
    { 0x002F01C4, "GENSIO_END_TRANSACTION" },  // nokix
    { 0x002F0244, "UI_HANDLER1" },  // nokix
    { 0x002F05B0, "__TRUNCDFSF2" },  // nokix
    { 0x002F05FC, "__FIXDFSI" },  // nokix
    { 0x002F0644, "FLOAT_CMP" },  // nokix
    { 0x002F0718, "ATOI" },  // nokix
    { 0x002F0820, "__FIXUNSDFSI" },  // nokix
    { 0x002F0860, "__FLOATSISF" },  // nokix
    { 0x002F08D8, "__EXTENDSFDF2" },  // nokix
    { 0x002F098E, "GU_DSP_BOOTREADY_SET" },  // overlay — sets boot-ready flag [0x111861]=1 + publishes msg3 to lists 0x32EB50/54 [DIS][XARM exact 8850 0x30C7EA + 7110 0x4EFD56]
    { 0x002F09C0, "__FIXSFSI" },  // nokix
    { 0x002F0A94, "__FIXUNSSFSI" },  // nokix
    { 0x002F0B4C, "__FLOATSIDF" },  // nokix
    { 0x002F0BA4, "FATAL_HANDLER" },  // overlay — ARM exception vector trampoline -> reason 5
    { 0x002F0BC8, "FATAL_RESUME_THUMB" },  // overlay — transition point in fatal handler [13:01]
    { 0x002F0BCC, "RAND" },  // nokix
    { 0x002F0BE0, "SRAND" },  // nokix
    { 0x002F0BF4, "__FLOATUNSISF" },  // nokix
    { 0x002F0C1C, "GU_SIMUPL_TASK" },  // overlay — SIM upper-layer task20 entry: GET_TASK_MESSAGE 0xC0..0x1D2 window, dispatch 0x2474DC [DIS][DATA slot20][XREF]
    { 0x002F0C40, "__FLOATUNSIDF" },  // nokix
    { 0x002F0D4C, "TOUPPER" },  // nokix
    { 0x002F0DC4, "TOLOWER" },  // nokix
    { 0x002F0DE8, "ISDIGIT" },  // nokix
    { 0x002F0E08, "ATOF" },  // nokix
    { 0x002F0E1C, "RAM_INIT_DATA" },  // nokix
    { 0x002F2044, "GU2_SIMLOCK_ROM_INIT" },  // overlay — flash ROM .data scatter-load descriptor [be32 len=0x12][be32 dst=0x10EB48][8xEE 10xFF]: static BOOT-DEFAULT init of rec0 reject-all (compare=8xEE, enable[+8]=FF, status[+17]=FF), in the 210-desc RAM-init table 0x2F1060..0x2F22CC. This is the DEFAULT; 0x287BE8 later overwrites records from DSP-decoded message payload [DATA]
    { 0x002F2258, "DSP_BLOCK_DESC_TABLE" },  // overlay — NULL-terminated table of 28 BE flash pointers to DSP code-block descriptors (0x300CD8-0x307DFC); IRQ4 upload handshake indexes this [22:09]
    { 0x00310A2C, "NETMON_D39_RESETCNT_LAYOUT" },  // overlay — PDF D39 reset-reason counters UN WD DSP SIM IDLE STACK, label 0x2283C4 - has DSP column [00:50]
    { 0x00310D3C, "NETMON_D70_DSPTEMP_LAYOUT" },  // overlay — PDF D70 DSP temporary counters TR1 TR2 TRA TC, label 0x2286E0, field ids 0x11D-0x122 [00:50]
    { 0x00310D74, "NETMON_D71_DSPTEMP2_LAYOUT" },  // overlay — NetMon D71 Temporary DSP counters, label 0x228710 [00:50]
    { 0x00310E54, "NETMON_D75_SIGLEVEL_LAYOUT" },  // overlay — NetMon D75 DSigL USigL downlink/uplink DSP signal level, label 0x228798 [00:50]
    { 0x00310E88, "NETMON_D76_EXTAUD_LAYOUT" },  // overlay — NetMon D76 ExtAudStatus external audio/DSP status, label 0x2287C0 [00:50]
    { 0x00310F1C, "NETMON_D79_ECHO_LAYOUT" },  // overlay — NetMon D79 EAA Ada ERL echo-canceller DSP, label 0x228828 [00:50]
    { 0x003113E4, "NETMON_D131_DSPRESETCNT_LAYOUT" },  // overlay — NetMon D131 DSP resetcnt dedicated DSP reset counter, label 0x228B70 [00:50]
    { 0x003114E0, "NETMON_DISPLAY_TABLE" },  // overlay — master display table 71 entries 12B = layout+label+num, displays D2-D133, lookup base 0x3114DC used by 0x227612 [00:50]
    { 0x00311A18, "NETMON_FIELD_TABLE" },  // overlay — field-def table 8B entries word0=RAMaddr-or-getterfn byte5=type1u8/3getter/4s16/8u16/9pct byte6=unit-char, ~32 entries battery+charging group [00:50]
    { 0x00311C34, "NETMON_RESET_REASON_TABLE" },  // overlay — 6x8B [code][b1][name5]: 6B=SWWD 01=UNKNO 68=SWDSP 69=SWSIM 6C=SWIDL 06=STACK [00:15]
    { 0x00313428, "ACTIONS_TABLE" },  // nokix
    { 0x003174F8, "PPM_STRINGS_TABLE" },  // nokix
    { 0x0031C30C, "TASKS_INIT_TABLE" },  // nokix
    { 0x00321EA0, "DISPATCHERS_TABLE" },  // nokix
    { 0x0032ACBC, "GU2_M2D_FREQBAND_TLV_TABLE" },  // overlay — flash 30x4 band-key table; 0x24E09C matches [+0]==key,[+1]==2 -> 2B record appended to m2d neighbour frame as 0x7F TLV [DATA][DIS]
    { 0x0032C2CC, "SWDSP_MSGID_TABLE" },  // overlay — 32-bit BE id table, index=(state*9+col)->id 0xFCD..0x100B; 0x1004(state6/col1) at +0x8C. INVERSE of recv-loop state=(id-0xFCD)/9. Action table 0x32C3DC. NB does NOT cancel the watchdog (refuted) [06:36]
    { 0x0032C4E8, "BROKER_TRACE_CHANNEL_TABLE" },  // overlay — trace-channel NAME registry (osmocom dct3-gsmtap taxonomy); entries 8F<idx> <fixedlen> 00; idx 0x18=MDISND 0x19=MDIRCV 0x20/0x23=SIM (EXACT match to dct3-gsmtap types). VESTIGIAL in v5.79: ref'd ONLY by dead BROKER_CHANNEL_PUBLISH_DEAD 0x2EC3FA literal pool; NOT wired at runtime. Live publish uses native event-ids via BROKER_ROUTER_SPINE 0x2EACAA [16:31][16:52]
    { 0x0032CB10, "GU2_SIM_EF_DESC_TABLE" },  // overlay — SIM EF file-map {file_id BE, length BE
    { 0x0032D535, "_CTYPE_" },  // nokix
    { 0x0032D6B8, "BATTERY_BAR_CONV_TABLE" },  // overlay — battery mV->bar thresholds; 14 words in mV (0xC1C=3100..0xF06=3846); 4 temp-variant tables stepping -0x20 [20:13]
    { 0x0032D6D8, "NET_TRIGCONV_TABLE" },  // overlay — NokiX trigconv sig 0064004B0032...; network-strength conversion table (8 words) [20:13]
    { 0x0032D6D9, "GU3_NET_TRIGCONV_DISPBYTE" },  // overlay — display-value byte array = low bytes of NET_TRIGCONV_TABLE BE halfwords (100,75,50,25,25,25,25,25), indexed by bar level*2, read 0x2A21B2 [DATA] [21:46]
    { 0x0032D738, "DATETIME_ZERO" },  // nokix
    { 0x0032E1E4, "GU2_LAPDM_FILL_TEMPLATE" },  // overlay — 23-byte idle/fill LAPDm frame: 01 03 01 + 20x 0x2B fill; L2 overwrites with real L3 before send [DATA][OMEGA47 9.1]
    { 0x0032E318, "TASK_POOL_BASE_TABLE" },  // overlay — flash per-task RAM pool-base ptr table indexed by [0x104845] (H5 09-03) [20:13]
    { 0x0032E6F8, "NETMON_CHANTYPE_TOKENS" },  // overlay — PDF D1 oooo channel-type token-ptr table, 8 entries each a PPM string-index list, used 0x26ADDE [00:35]
    { 0x0032E820, "PPM_STRUCT" },  // nokix
    { 0x00340000, "PPM" },  // nokix
    { 0x00393EC4, "GET_BLINK_BUFFER" },  // nokix
    { 0x00393ED4, "WIN_ALIGN_PARTS" },  // nokix
    { 0x00393EEC, "DIALOG_PHONE_GET_PHONE" },  // nokix
    { 0x00393EF8, "DIALOG_PHONE_GET_NAME" },  // nokix
    { 0x00393F08, "BLZ_DEPACKED_SIZE" },  // nokix
    { 0x00393F0C, "BLZ_DEPACK" },  // nokix
    { 0x00393F20, "IFF_CREATE" },  // nokix
    { 0x00393F3C, "IFF_ADD_CHUNK" },  // nokix
    { 0x00393F64, "BLZ_MAX_PACKED_SIZE" },  // nokix
    { 0x00393F6E, "BLZ_PACK" },  // nokix
    { 0x00393F8A, "PC1_CRYPT" },  // nokix
    { 0x00393FBC, "IFF_REM_CHUNK" },  // nokix
    { 0x00393FDC, "PC1_DECRYPT" },  // nokix
    { 0x00394048, "OWN_ALPHANUMERIC_KEYBOARD" },  // nokix
    { 0x003CFFFF, "PPM_END" },  // nokix
};
static const int dct3_symbols_3310_v579_n =
    (int)(sizeof(dct3_symbols_3310_v579) / sizeof(dct3_symbols_3310_v579[0]));

// Find the symbol with the largest addr <= target. Returns the index, or -1
// if target is below the first entry. O(log N) binary search. The caller can
// compute (target - table[idx].addr) to surface the offset (e.g. "FOO + 12").
static inline int dct3_symbols_3310_v579_nearest(uint32_t target) {
    int lo = 0, hi = dct3_symbols_3310_v579_n - 1, best = -1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        if (dct3_symbols_3310_v579[mid].addr <= target) { best = mid; lo = mid + 1; }
        else hi = mid - 1;
    }
    return best;
}

#endif // DCT3_SYMBOLS_3310_V579_H
