// AUTO-GENERATED by tools/symbols/gen_c_table.py 7110-v500
// DO NOT EDIT. Regenerate after refreshing tools/symbols/7110-v500.*.yaml.
//
// Sorted (addr, name) table for 7110-v500 (49 entries).
// Used by mad2's post-mortem caller-LR labeller (src/mad2/mad2.c) when
// the hand-coded label table doesn't match — falls back to nearest-symbol
// (binary-search-friendly because the array is addr-sorted).

#ifndef DCT3_SYMBOLS_7110_V500_H
#define DCT3_SYMBOLS_7110_V500_H

#include <stdint.h>

typedef struct {
    uint32_t    addr;     // flash address (Thumb bit stripped — match LR & ~1u)
    const char *name;     // semantic name (overlay > nokix; first wins on tie)
} Dct3Symbol;

static const Dct3Symbol dct3_symbols_7110_v500[] = {
    { 0x0026F684, "SELFTEST_STEP_DESC_TABLE" },  // overlay — 9-step DSP measurement descriptor table: {0600 0505,0600 0604,0600 0700,0701 09A5,0701 0AA4,0701 0BA0,0600 0D05,0600 0E04,0600 0F00
    { 0x002813AD, "_CTYPE_" },  // nokix
    { 0x00283C94, "DATETIME_ZERO" },  // nokix
    { 0x0028D854, "MCU_VERSION_STRING" },  // nokix
    { 0x0028DC94, "KEYPAD_KEYMAP_TABLE" },  // overlay — 5x5 keypad keymap (rawkey=row*5+col -> keycode); 0x5A=dead. Digits 0x01-0x09=1-9, 0x0A=0, 0x0B=#, 0x0C=*, 0x19=SOFT1, 0x1A=SOFT2, 0x0E=SEND, 0x0F=END, 0x12=roller-press [17:18]
    { 0x002A7546, "FREE" },  // nokix
    { 0x002C5364, "UI_HANDLER1" },  // nokix
    { 0x002DAAE2, "UI_HANDLER2" },  // nokix
    { 0x0030DE18, "SELFTEST_VERDICT_BUILDER" },  // overlay — builds verdict [0x17FE15]: sets bit3|bit6|bit7 unconditionally, bit0 iff ADC latch [0x16BC7C]==0, PASS/FAIL on leaf 0x49F548 ([0x167030]) [21:09]
    { 0x0030DEAC, "SELFTEST_FAILMARK_1415" },  // overlay — builder FAIL branch writes fail codes item[14]=0x0E item[15]=0x0F (the [0x167030] gate fail marker) [21:09]
    { 0x0030DF6A, "SELFTEST_TALLY_LOOP" },  // overlay — items 0..23 @0x17FC60: any value not in {0x00,0xFE,0xFF
    { 0x0030E06C, "SELFTEST_DSP74_HANDLER" },  // overlay — processes DSP type-0x74 records by sub [msg+8]: 0x0A/0xC8->0x30E166, 0x0D/0xD0->0x30E0EA, 0x10,0x33,0x34,0x35,0x36 arms; DEFAULT rewraps sub as INTERNAL dispatcher subop w/ payload (so DSP rec sub-0x64 payload[0]=2 = begin-handshake!) [21:09]
    { 0x0030E0EA, "SELFTEST_INCOMPLETE_ARM" },  // overlay — sub-0x0D/0xD0 arm: iff verdict bit3 set -> clear bit2, zero item[15], publish 0x8902 w/ table 0x26F9A4 (the CS/incomplete broadcast) [21:09]
    { 0x0030E14C, "SELFTEST_BIT5_GATE" },  // overlay — internal begin-msg sender 0x30E15A gated on verdict bit5 (no internal bit5 setter; DSP rewrap path bypasses this) [21:09]
    { 0x0030E166, "SELFTEST_DSP_MEAS_RESULT_ARM" },  // overlay — DSP74 handler arm (sub 0x0A/0xC8): reads measured value [rec+11], forwards via 0x45BA5E — the per-step measurement-result record that advances the step engine [21:45]
    { 0x0030E748, "SELFTEST_BIT3_SETCLEAR" },  // overlay — arg 0=clear bit3 / 1=set bit3, echoes internal subop-0xA4 msg; sole bit3 clear site 0x30E772 [21:09]
    { 0x0030F180, "SELFTEST_STEP_ENGINE" },  // overlay — internal subop-0x80 arm: walks descriptor table @0x26F684, issues cmd-8/cmd-9 pairs via 0x432B00, posts subop-0xA4 on completion (clears bit3) [21:09]
    { 0x00310490, "SELFTEST_RESULT_REPLY" },  // overlay — builds subop-0x64 reply msg [10]=verdict bit7 [11]=55 [12]=13.. (status report to requester) [21:09]
    { 0x0031070E, "SELFTEST_DISPATCH_BIT0_GATE" },  // overlay — dispatcher processes subops (except 0x64 begin) ONLY if verdict bit0 set; bit0-clear fallback 0x310B88 accepts only 0x72/0x7C/0xC8, else 0xFF error. REFUTES June 'bit0 moot' — bit0 (ch4<50 ADC gate) is REQUIRED for self-test completion [21:12]
    { 0x00310B52, "SELFTEST_BEGIN_HANDSHAKE" },  // overlay — subop-0x64 arm: iff bit3 set AND msg[9]==2 -> save requester task [0x16BCC8], set verdict bit4 [21:09]
    { 0x00310BFC, "SELFTEST_VERDICT_FINALIZE" },  // overlay — self-test task verdict-finalize (contains CS sequencer 0x310D5A); called from task main-loop 0x310E46 on internal control code [0xC0,0x1BF]; bit3 set -> CONTACT SERVICE, bit3 clear + [0x17FE1E]==2 -> standby [21:45]
    { 0x00310D5A, "SELFTEST_CS_SEQUENCER" },  // overlay — sequencer: reads verdict [0x17FE15], if bit3 set clears bit6/bit2/bit7 -> CONTACT SERVICE (0x310D7E); reads requester [0x16BCC8]@0x310D9A [21:24]
    { 0x00310E38, "SELFTEST_TASK_ROUTER" },  // overlay — self-test manager msg router: type@[msg+3]: 0x40->subop dispatcher 0x310F2E, 0x74->DSP record arm 0x310EDA, 0x42->0x310F12 [21:09]
    { 0x0031C30C, "TASKS_INIT_TABLE" },  // nokix
    { 0x0032E820, "PPM_STRUCT" },  // nokix
    { 0x00358DA0, "PRINT_TEXT" },  // nokix
    { 0x00358E20, "DRAW_BITMAP" },  // nokix
    { 0x00359088, "LCD_FLUSH_SHADOW" },  // overlay — copies shadow fb 0x154FE0 masked by 0x154C80 to SED1565 data port, polls GENSIO ready per byte, early-out if [0x154C38]==1 [15:40]
    { 0x00359356, "DRAW_PIXEL" },  // nokix
    { 0x00359644, "DRAW_LINE" },  // nokix
    { 0x00359CB4, "DRAW_BOX" },  // nokix
    { 0x0035A0F8, "LCD_FULL_REDRAW" },  // overlay — full-screen redraw+flush, gated on dirty flag [0x154C3E]==0xFF, callers 0x35A526/0x393B42/0x393B78/0x393C6C [15:40]
    { 0x00392E90, "DISPLAY_TASK_RECV" },  // overlay — recv wrapper, translates raw codes 192/193/196/198 via RAM cells [16:11]
    { 0x00393104, "DISPLAY_TASK_MAIN" },  // overlay — display server task entry, blocks at 0x393118 recv-loop until startup event 0xB1/177 then charge-classifies boot mode [16:11]
    { 0x003BAD7A, "UI_DIALOG" },  // nokix
    { 0x003BB120, "SEMAPHORE_OPEN" },  // nokix
    { 0x003BB77C, "SEND_TASK_MESSAGE" },  // nokix
    { 0x003BB830, "TASK_RECV" },  // overlay — RTOS per-task event recv, task id [0x100022], TCB 0x101A84+id*28, ring 0x126BB8+id*16 [16:11]
    { 0x003BBB40, "TASKS_INIT" },  // nokix
    { 0x003BBE28, "MALLOC_TRY" },  // nokix
    { 0x003BBF98, "MALLOC" },  // nokix
    { 0x003BC060, "EEPROM_READ_BYTES" },  // nokix
    { 0x003E0EAE, "SEMAPHORE_CLOSE" },  // nokix
    { 0x003E3B3A, "XBUS_CONNECT" },  // nokix
    { 0x003E3E5A, "XBUS_GET_CONNECTION" },  // nokix
    { 0x003F5DB2, "UI_PROCESSOR" },  // nokix
};
static const int dct3_symbols_7110_v500_n =
    (int)(sizeof(dct3_symbols_7110_v500) / sizeof(dct3_symbols_7110_v500[0]));

// Find the symbol with the largest addr <= target. Returns the index, or -1
// if target is below the first entry. O(log N) binary search. The caller can
// compute (target - table[idx].addr) to surface the offset (e.g. "FOO + 12").
static inline int dct3_symbols_7110_v500_nearest(uint32_t target) {
    int lo = 0, hi = dct3_symbols_7110_v500_n - 1, best = -1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        if (dct3_symbols_7110_v500[mid].addr <= target) { best = mid; lo = mid + 1; }
        else hi = mid - 1;
    }
    return best;
}

#endif // DCT3_SYMBOLS_7110_V500_H
