// AUTO-GENERATED by tools/symbols/gen_c_table.py 8850-v531
// DO NOT EDIT. Regenerate after refreshing tools/symbols/8850-v531.*.yaml.
//
// Sorted (addr, name) table for 8850-v531 (197 entries).
// Used by mad2's post-mortem caller-LR labeller (src/mad2/mad2.c) when
// the hand-coded label table doesn't match — falls back to nearest-symbol
// (binary-search-friendly because the array is addr-sorted).

#ifndef DCT3_SYMBOLS_8850_V531_H
#define DCT3_SYMBOLS_8850_V531_H

#include <stdint.h>

typedef struct {
    uint32_t    addr;     // flash address (Thumb bit stripped — match LR & ~1u)
    const char *name;     // semantic name (overlay > nokix; first wins on tie)
} Dct3Symbol;

static const Dct3Symbol dct3_symbols_8850_v531[] = {
    { 0x002001D0, "__CTYPE_PTR" },  // nokix
    { 0x002001FC, "MCU_VERSION_STRING" },  // nokix
    { 0x002002F2, "FREE" },  // nokix
    { 0x0023A3E0, "GET_DATE_FORMAT" },  // nokix
    { 0x00240B60, "VERDICT_BIT2_WRITER" },  // overlay — sets MMI_READY_VERDICT bit2 ST-pending after streaming self-test request to DSP bl 0x284E28 [08:11]
    { 0x0025EBC6, "WIN_GET_PART_INFO" },  // nokix
    { 0x0025EC06, "WIN_MARK_INFO_DIRTY" },  // nokix
    { 0x0025EF10, "WIN_ALIGN_INFOS" },  // nokix
    { 0x0025F12E, "WIN_PRINT" },  // nokix
    { 0x00265334, "AORD_GET_NEXT_CHAR" },  // nokix
    { 0x00270164, "DIALOG_CLOSE" },  // nokix
    { 0x002701E4, "DIALOG_OPEN_MSG" },  // nokix
    { 0x002703A4, "DIALOG_OPEN" },  // nokix
    { 0x0027A520, "MENU_GET_ITEM" },  // nokix
    { 0x0027A566, "MENU_DELETE" },  // nokix
    { 0x0027A5A6, "MENU_REM_ITEM" },  // nokix
    { 0x0027B488, "MENU_OPEN" },  // nokix
    { 0x0027B654, "MENU_ADD_ITEM" },  // nokix
    { 0x0027C244, "OPEN_STATIC_MENU" },  // nokix
    { 0x0027EE28, "PRINT_TEXT" },  // nokix
    { 0x0027EEF8, "DRAW_BOX" },  // nokix
    { 0x0027F33C, "DRAW_PIXEL" },  // nokix
    { 0x0027F3C6, "DRAW_BITMAP" },  // nokix
    { 0x0027FA80, "DRAW_LINE" },  // nokix
    { 0x0027FD58, "GET_FONT" },  // nokix
    { 0x002885BC, "SEND_TASK_MESSAGE" },  // nokix
    { 0x00288A7C, "TASKS_INIT" },  // nokix
    { 0x00288E54, "MALLOC_TRY" },  // nokix
    { 0x002890A8, "MALLOC" },  // nokix
    { 0x0028923C, "EEPROM_READ_BYTES" },  // nokix
    { 0x002AB194, "PLAY_ANY_TONE" },  // nokix
    { 0x002B7A20, "XBUS_CONNECT" },  // nokix
    { 0x002B7B70, "XBUS_GET_CONNECTION" },  // nokix
    { 0x002CB418, "DSP_IRQ4_ISR" },  // overlay — IRQ4 DSP mailbox ISR sets DSP_UPLOADED 0x135664 when reply reg 0x100E4==0 [08:11]
    { 0x002CDD66, "FTOA" },  // nokix
    { 0x002E3510, "WCSSCAT" },  // nokix
    { 0x002E3EFC, "GET_TIMESTAMP" },  // nokix
    { 0x002ED090, "UPPER_REFRESH" },  // nokix
    { 0x002ED480, "UPPER_MODE" },  // nokix
    { 0x002ED550, "UPPER_REM" },  // nokix
    { 0x002ED5C4, "UPPER_SET" },  // nokix
    { 0x002EF0D8, "NTOA2" },  // nokix
    { 0x002EF358, "ADD_TIME" },  // nokix
    { 0x002EF408, "ADD_DATE" },  // nokix
    { 0x002EF514, "ADD_DATETIME" },  // nokix
    { 0x002F5514, "DISPLAY_MSG" },  // nokix
    { 0x002F6E6C, "REASON_SETTER" },  // overlay — standalone reason-stamp leaf strb r0 to REBOOT_REASON analog 3310 0x2E0ED8 [11:17]
    { 0x002FA94E, "EEPROM_WRITE" },  // nokix
    { 0x002FA994, "EEPROM_READ" },  // nokix
    { 0x002FAEF8, "SET_LIGHTS" },  // nokix
    { 0x002FB496, "SEMAPHORE_OPEN" },  // nokix
    { 0x003014F6, "SEND_UI_MESSAGE" },  // nokix
    { 0x003015C0, "KEYPAD_RAW_READ" },  // overlay — raw keypad IO reader cols 0x2002A rowdir 0x200A8 [08:52]
    { 0x00302506, "XBUS_SEND_FRAME" },  // nokix
    { 0x00303CE2, "FIND_PPM" },  // nokix
    { 0x00303D00, "FIND_PPM_CHUNK" },  // nokix
    { 0x003040E4, "STR2DOUBLE_EX" },  // nokix
    { 0x00304596, "GENSIO_SET_COORD" },  // nokix
    { 0x0030540A, "KEYPAD_DECODE" },  // overlay — keypad scan+decode reads raw via 0x3015C0 indexes KEYMAP_NORM [08:52]
    { 0x003091C8, "__SUBDF3" },  // nokix
    { 0x003091D2, "__ADDDF3" },  // nokix
    { 0x00309D66, "REBOOT_FN" },  // overlay — universal reboot fn r0=reason persists to REBOOT_REASON writes 0x20001 bit2 then spins analog 3310 0x2EEBAE [11:17]
    { 0x0030A69E, "SET_ACTION" },  // nokix
    { 0x0030A810, "__MULDF3" },  // nokix
    { 0x0030A944, "EEPROM_WRITE_BYTES" },  // nokix
    { 0x0030AE48, "DIVMOD" },  // nokix
    { 0x0030B060, "__SUBSF3" },  // nokix
    { 0x0030B06A, "__ADDSF3" },  // nokix
    { 0x0030B59C, "UDIVMOD" },  // nokix
    { 0x0030B634, "DELAY" },  // nokix
    { 0x0030BB80, "__MULSF3" },  // nokix
    { 0x0030BBF8, "DOUBLE_CMP" },  // nokix
    { 0x0030BDD4, "DRAW_CHARS" },  // nokix
    { 0x0030BE14, "GENSIO_END_TRANSACTION" },  // nokix
    { 0x0030C3C4, "__TRUNCDFSF2" },  // nokix
    { 0x0030C45C, "__FIXDFSI" },  // nokix
    { 0x0030C4EC, "FLOAT_CMP" },  // nokix
    { 0x0030C600, "ATOI" },  // nokix
    { 0x0030C644, "__FIXUNSDFSI" },  // nokix
    { 0x0030C684, "__FLOATSISF" },  // nokix
    { 0x0030C6FC, "__EXTENDSFDF2" },  // nokix
    { 0x0030C7AC, "__FIXSFSI" },  // nokix
    { 0x0030C8B8, "__FIXUNSSFSI" },  // nokix
    { 0x0030C9C8, "__FLOATSIDF" },  // nokix
    { 0x0030CA4C, "__FLOATUNSISF" },  // nokix
    { 0x0030CA74, "RAND" },  // nokix
    { 0x0030CA88, "SRAND" },  // nokix
    { 0x0030CA9C, "FATAL_HANDLER" },  // overlay — ARM fatal-exception entry resolves via shared sig [11:17]
    { 0x0030CB0C, "__FLOATUNSIDF" },  // nokix
    { 0x0030CC0C, "TOUPPER" },  // nokix
    { 0x0030CC48, "TOLOWER" },  // nokix
    { 0x0030CC6C, "ISDIGIT" },  // nokix
    { 0x0030CC8C, "ATOF" },  // nokix
    { 0x0030CCB0, "RAM_INIT_DATA" },  // nokix
    { 0x0032CD68, "ACTIONS_TABLE" },  // nokix
    { 0x0032E2E8, "PPM_STRINGS_TABLE" },  // nokix
    { 0x0033586C, "DISPATCHERS_TABLE" },  // nokix
    { 0x0033DF21, "_CTYPE_" },  // nokix
    { 0x0033E2DC, "DATETIME_ZERO" },  // nokix
    { 0x0033F504, "KEYMAP_NORM" },  // overlay — keypad normal-scan keycode table 25 entries row*5+col [08:52]
    { 0x0033F520, "KEYMAP_SPEC" },  // overlay — keypad special-scan keycode table POWER at idx4 [08:52]
    { 0x0033F5E0, "PPM_STRUCT" },  // nokix
    { 0x00340000, "PPM" },  // nokix
    { 0x003CFFFF, "PPM_END" },  // nokix
    { 0x003D0010, "AORD_STRICMP" },  // nokix
    { 0x003D0014, "GET_BLINK_BUFFER" },  // nokix
    { 0x003D0024, "WIN_ALIGN_PARTS" },  // nokix
    { 0x003D003C, "DIALOG_PHONE_GET_PHONE" },  // nokix
    { 0x003D0048, "DIALOG_PHONE_GET_NAME" },  // nokix
    { 0x003D0058, "BLZ_DEPACKED_SIZE" },  // nokix
    { 0x003D005C, "BLZ_DEPACK" },  // nokix
    { 0x003D0070, "IFF_CREATE" },  // nokix
    { 0x003D008C, "IFF_ADD_CHUNK" },  // nokix
    { 0x003D00B4, "BLZ_MAX_PACKED_SIZE" },  // nokix
    { 0x003D00BE, "BLZ_PACK" },  // nokix
    { 0x003D00DA, "PC1_CRYPT" },  // nokix
    { 0x003D010C, "IFF_REM_CHUNK" },  // nokix
    { 0x003D012C, "PC1_DECRYPT" },  // nokix
    { 0x003D0198, "OWN_ALPHANUMERIC_KEYBOARD" },  // nokix
};
static const int dct3_symbols_8850_v531_n =
    (int)(sizeof(dct3_symbols_8850_v531) / sizeof(dct3_symbols_8850_v531[0]));

// Find the symbol with the largest addr <= target. Returns the index, or -1
// if target is below the first entry. O(log N) binary search. The caller can
// compute (target - table[idx].addr) to surface the offset (e.g. "FOO + 12").
static inline int dct3_symbols_8850_v531_nearest(uint32_t target) {
    int lo = 0, hi = dct3_symbols_8850_v531_n - 1, best = -1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        if (dct3_symbols_8850_v531[mid].addr <= target) { best = mid; lo = mid + 1; }
        else hi = mid - 1;
    }
    return best;
}

#endif // DCT3_SYMBOLS_8850_V531_H
