// AUTO-GENERATED by tools/symbols/gen_c_table.py 3210-v600
// DO NOT EDIT. Regenerate after refreshing tools/symbols/3210-v600.*.yaml.
//
// Sorted (addr, name) table for 3210-v600 (37 entries).
// Used by mad2's post-mortem caller-LR labeller (src/mad2/mad2.c) when
// the hand-coded label table doesn't match — falls back to nearest-symbol
// (binary-search-friendly because the array is addr-sorted).

#ifndef DCT3_SYMBOLS_3210_V600_H
#define DCT3_SYMBOLS_3210_V600_H

#include <stdint.h>

typedef struct {
    uint32_t    addr;     // flash address (Thumb bit stripped — match LR & ~1u)
    const char *name;     // semantic name (overlay > nokix; first wins on tie)
} Dct3Symbol;

static const Dct3Symbol dct3_symbols_3210_v600[] = {
    { 0x00208134, "MEAS_TASK_BODY" },  // overlay — broker-driven measurement task body; sets alive-flag [0x111C93] (3310 0x21D610, sub-id 0x4B43->3210 0x4943); NEVER RUNS on 3210
    { 0x002346B2, "VERDICT_BUILDER" },  // overlay — verdict/cksum builder over [0x11FE68] struct (5110 0x22EC10 twin)
    { 0x0023475C, "CS_VERDICT_BIT7_SET" },  // overlay — sole writer that SETS [0x11FED1] bit7 (one-shot boot grace token)
    { 0x00236DC4, "SCREEN_READY_GATE" },  // overlay — MMI screen-ready gate (5110 0x231148 twin); reads [0x11FED1]
    { 0x00237ADE, "STARTUP_SM_DISPATCH" },  // overlay — startup-screen SM bit-dispatch on [0x11FED1]; bit2 set -> [0x11FC6F]=15 RUNNING @0x237AF8
    { 0x00237B52, "CS_DISPLAY_GATE" },  // overlay — CONTACT SERVICE display decision: ldr=0x11FE68; ldrb [0x69+r5]=[0x11FED1]; lsr#7; bcs — bit7 SET=standby, CLEAR=draw 'CONTACT SERVICE'
    { 0x00237CC4, "CS_STRING_INLINE" },  // overlay — inline ASCII 'CONTACT\\0SERVICE\\0' (NOT a PPM string); loaded PC-rel @0x237B62
    { 0x002520EC, "READINESS_AGGREGATOR" },  // overlay — readiness aggregator (11 flags [0x112280..8A]); completes ~4.28M; 3310 0x278670 twin
    { 0x0026A354, "TASK_SEND_3210" },  // overlay — TASK_SEND primitive (3310 0x29921C twin)
    { 0x002701C0, "LAUNCH_SUBDISPATCH" },  // overlay — coordinator sub-state dispatch (reads [0x1123EE/EF])
    { 0x00270848, "VBATT_WINDOW_GATE" },  // overlay — VBATT window gate [0x2BE..0x314] (accept) @0x2708A6
    { 0x00270C8C, "BOOT_COORD_LOOP" },  // overlay — boot coordinator (task 1) loop; jump-table 0x270CA8
    { 0x00270E1C, "BOOT_COORD_RECV" },  // overlay — coordinator TASK_RECV + sub-state store -> [0x1123EF]
    { 0x0028FF14, "READINESS_CHECK3" },  // overlay — readiness check-3: needs [0x111C93]!=0 (+ [0x10DCAE]=1/[0x10D1C0]=0/[0x10DCB0]); 3310 0x2BA304 twin. THE remaining gate
    { 0x00290C9A, "DSP_UPLOADED_SETTER" },  // overlay — DSP-block-loader setter: strb r4,[r8] r8=0x110C2C (= .dsp_uploaded)
    { 0x0029BC70, "STARTUP_SM_PROCEED_EVAL" },  // overlay — startup-screen proceed eval: consumes [0x11FED1] bit7 (@0x29BC8A), does proceed-to-running ONLY IF [0x112448]==0 (gate @0x29BC92)
    { 0x002A689C, "BATT_TASKSEND_19" },  // overlay — no-fault ch4-lt-26 path TASK_SEND task19 msg 0x44 [10:42]
    { 0x002A68C6, "BSI_READER" },  // overlay — BSI reader — CCONT logical ch1; recognised-pack interpolation
    { 0x002A84B0, "VBATT_BOOT_READER" },  // overlay — VBATT boot reader (5-sample avg), CCONT logical ch0
    { 0x002A8FF2, "CHARGE_STATE_FN" },  // overlay — charge-state fn (entry); contains the BTEMP gate; caller 0x2A92DC
    { 0x002A90AC, "BTEMP_GATE" },  // overlay — BTEMP gate: read CCONT A/D ch4 (0x2B52CC); cmp#26 @0x2A90B0; <26 -> [0x112448]=0 PROCEED else =2 STUCK(CONTACT SERVICE)
    { 0x002A9278, "REASON_SETTER_3210" },  // overlay — sets cold reason [0x11FF41]=0x0A from [0x020001] bit0
    { 0x002A92FC, "READINESS_SEQUENCER" },  // overlay — power-up readiness sequencer (re-poll); PASS 0x2A934C, not-ready/spin 0x2A933A/0x2A9344; 3310 IDLE_LOOP_BACK 0x2E0E32 twin
    { 0x002A9368, "CHARGE_STATE_GETTER" },  // overlay — ldrb r0,[0x112448]; mov pc,lr — charge/battery-fault state getter
    { 0x002A936E, "REBOOT_REASON_SETTER" },  // overlay — strb r0,[0x11FF50] — stages reboot reason
    { 0x002AF0AE, "POWERON_CLASSIFIER" },  // overlay — reason-10 power-on classifier: reads CCONT reg 0x0E; bit7->RTC-alarm, bit2->mode1, bit1->mode2(normal PWR)
    { 0x002AF208, "READINESS_AGG_COMPLETE" },  // overlay — aggregator completion call (post all-ready)
    { 0x002B0860, "VCHAR_PRESENT_TEST" },  // overlay — VCHAR charger-present test: cmp#100 bgt=present @0x2B0866
    { 0x002B4F2E, "BTEMP_CLASSIFIER" },  // overlay — BTEMP classifier: cmp#39 blt=normal(144) else fault(0x141)
    { 0x002B52CC, "CCONT_AD_READER" },  // overlay — CCONT A/D reader: r0=logical channel; returns 10-bit value (descriptor tbl 0x2E2DA8)
    { 0x002B5446, "SOFTFLOAT_FADD" },  // overlay — soft-float add [10:42]
    { 0x002B59E0, "SOFTFLOAT_FMUL" },  // overlay — soft-float multiply [10:42]
    { 0x002B63CC, "SOFTFLOAT_F2I" },  // overlay — soft-float float-to-int [10:42]
    { 0x002B64FC, "SOFTFLOAT_I2F" },  // overlay — soft-float int-to-float IEEE bias 0x9E [10:42]
    { 0x002E2D58, "KEYMAP_TABLE" },  // overlay — 25-byte scancode-to-keycode table, drive*5+bit, +5 special block pwr=0x0D [22:52]
    { 0x002E2D74, "CH_MAP_TABLE" },  // overlay — flash: per-quantity->channel map {00 04 05 06 07 03 02 01
    { 0x002E2DA8, "CCONT_DESC_TABLE" },  // overlay — flash: CCONT A/D channel descriptor table (reg<<3|4 encoding)
};
static const int dct3_symbols_3210_v600_n =
    (int)(sizeof(dct3_symbols_3210_v600) / sizeof(dct3_symbols_3210_v600[0]));

// Find the symbol with the largest addr <= target. Returns the index, or -1
// if target is below the first entry. O(log N) binary search. The caller can
// compute (target - table[idx].addr) to surface the offset (e.g. "FOO + 12").
static inline int dct3_symbols_3210_v600_nearest(uint32_t target) {
    int lo = 0, hi = dct3_symbols_3210_v600_n - 1, best = -1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        if (dct3_symbols_3210_v600[mid].addr <= target) { best = mid; lo = mid + 1; }
        else hi = mid - 1;
    }
    return best;
}

#endif // DCT3_SYMBOLS_3210_V600_H
