#!/usr/bin/env python3
"""Bake the NokiX virgin external-I2C-EEPROM blobs into a compiled-in C array.

The early-MAD2 models (5110/6110/…) hang an external 24Cxx EEPROM off a bit-banged
serial bus instead of an in-flash EEPROM partition. src/mad2/ext_eeprom.c used to
fopen() the NokiX virgin blob at runtime — which works natively but NOT in the wasm
build (the file is not in the MEMFS), leaving the web EEPROM virgin 0xFF -> the boot
self-test reads garbage calibration -> CONTACT SERVICE. Baking the blobs in fixes the
web build and removes the file dependency; the model profile auto-selects its blob.

Source: ref/NokiX-scripts/NokiX/scripts/scripts/misc/repair_external_eeprom/*.bin
Output: src/mad2/ext_eeprom_blobs.{c,h}  (committed; regenerate with this script)

  ./tools/gen_ext_eeprom_blobs.py
"""
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Canonical location for the per-model virgin external-I2C-EEPROM images (brought up from the
# NokiX repair_external_eeprom set into firmware/ so they sit alongside the .fls images).
SRC_DIR = os.path.join(REPO, "firmware")
OUT_C = os.path.join(REPO, "src/mad2/ext_eeprom_blobs.c")
OUT_H = os.path.join(REPO, "src/mad2/ext_eeprom_blobs.h")

# NokiX file stem -> C symbol stem. (Nokia type designators: NSE-1 = 5110, etc.)
BLOBS = ["nse-1", "nse-3", "nse-6", "nse-8", "nsm-1"]

HDR = "// AUTO-GENERATED by tools/gen_ext_eeprom_blobs.py — DO NOT EDIT.\n"


def sym(stem):
    return "EE_" + stem.upper().replace("-", "")


def main():
    blobs = []
    for stem in BLOBS:
        path = os.path.join(SRC_DIR, stem + ".bin")
        with open(path, "rb") as f:
            data = f.read()
        blobs.append((stem, sym(stem), data))

    # --- header ---
    h = [HDR,
         "// Baked NokiX virgin external-I2C-EEPROM images, auto-selected per model\n",
         "// (ModelProfile.i2c_eeprom_default / .i2c_eeprom_size). See ext_eeprom.c.\n",
         "#ifndef DCT3_EXT_EEPROM_BLOBS_H\n#define DCT3_EXT_EEPROM_BLOBS_H\n",
         "#include <stdint.h>\n\n"]
    for stem, s, data in blobs:
        h.append(f"extern const uint8_t {s}[];   // NokiX {stem}.bin\n")
        h.append(f"#define {s}_LEN {len(data)}u\n")
    h.append("\n#endif\n")
    with open(OUT_H, "w") as f:
        f.write("".join(h))

    # --- source ---
    c = [HDR, '#include "mad2/ext_eeprom_blobs.h"\n\n']
    for stem, s, data in blobs:
        c.append(f"const uint8_t {s}[{len(data)}] = {{\n")
        for i in range(0, len(data), 16):
            row = ", ".join("0x%02X" % b for b in data[i:i + 16])
            c.append("    " + row + ",\n")
        c.append("};\n\n")
    with open(OUT_C, "w") as f:
        f.write("".join(c))

    total = sum(len(d) for _, _, d in blobs)
    print(f"[gen-ee] wrote {OUT_H} + {OUT_C}: {len(blobs)} blobs, {total} bytes")
    for stem, s, data in blobs:
        print(f"  {s:10s} = {stem}.bin ({len(data)} bytes)")


if __name__ == "__main__":
    sys.exit(main())
