// trace_names.h — runtime loader for our DCT3 broker/MDI trace-event name table
// (tools/symbols/trace-names-nhm5.txt). Maps 16-bit DCT3 broker event-ids (the
// value the firmware hands BROKER_ROUTER/BROKER_DELIVER in r1) to their functional
// names, e.g. 0x1802 -> "MDI:m2d/CHANNEL_CONFIGURE".
//
// The table is GPL-free: it holds only the bare id -> name FACTS (the firmware's
// own subsystem + GSM/protocol labels), regenerated by tools/symbols/gen_trace_names.py
// and normalized into our own format — see that table's header for the full
// provenance (facts cross-referenced from the public gammu/dct3trac NHM-5 dict, but
// no GPL text/structure reproduced). NHM-5 = 3310 family; the (type<<8)|subid
// taxonomy transfers across v5.79/v5.87. Override the path with $TRACENAMES (e.g.
// to point gen_trace_names.py's input back at a local copy for a refresh).
//
// Header-only, native tooling only (it reads a file; never compiled into wasm).
#ifndef DCT3_TRACE_NAMES_H
#define DCT3_TRACE_NAMES_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { unsigned short id; char name[72]; } TraceName;

static TraceName* g_tn = NULL;
static int g_tn_n = 0, g_tn_loaded = 0;

static int tn_cmp(const void* a, const void* b) {
    unsigned x = ((const TraceName*)a)->id, y = ((const TraceName*)b)->id;
    return (x > y) - (x < y);
}

// Parse the dictionary once. Lines are "HHHH CATEGORY:sub/NAME [extra]"; the
// "HHXX ..." category banners are skipped (their 3rd/4th chars are non-hex 'X').
static void trace_names_load(void) {
    if (g_tn_loaded) return;
    g_tn_loaded = 1;
    const char* path = getenv("TRACENAMES");
    if (!path) path = "tools/symbols/trace-names-nhm5.txt";
    FILE* f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "[brokerlog] trace name table not found: %s (decoding raw ids only)\n", path);
        return;
    }
    int cap = 2048;
    g_tn = (TraceName*)malloc((size_t)cap * sizeof(TraceName));
    char line[256];
    while (fgets(line, sizeof line, f)) {
        int ok = 1;
        for (int i = 0; i < 4; i++) {
            char ch = line[i];
            if (!((ch >= '0' && ch <= '9') || (ch >= 'A' && ch <= 'F') || (ch >= 'a' && ch <= 'f'))) { ok = 0; break; }
        }
        if (!ok || line[4] != ' ') continue;          // skip banners / blanks
        char h[5]; memcpy(h, line, 4); h[4] = 0;
        unsigned id = (unsigned)strtoul(h, NULL, 16);
        char* rest = line + 5;
        char* nl = strpbrk(rest, "\r\n");
        if (nl) *nl = 0;
        if (g_tn_n >= cap) { cap *= 2; g_tn = (TraceName*)realloc(g_tn, (size_t)cap * sizeof(TraceName)); }
        g_tn[g_tn_n].id = (unsigned short)id;
        strncpy(g_tn[g_tn_n].name, rest, sizeof(g_tn[g_tn_n].name) - 1);
        g_tn[g_tn_n].name[sizeof(g_tn[g_tn_n].name) - 1] = 0;
        g_tn_n++;
    }
    fclose(f);
    qsort(g_tn, (size_t)g_tn_n, sizeof(TraceName), tn_cmp);
    fprintf(stderr, "[brokerlog] loaded %d trace names from %s\n", g_tn_n, path);
}

static const char* trace_name_lookup(unsigned short id) {
    if (!g_tn) return NULL;
    int lo = 0, hi = g_tn_n - 1;
    while (lo <= hi) {
        int m = (lo + hi) >> 1;
        if (g_tn[m].id == id) return g_tn[m].name;
        if (g_tn[m].id < id) lo = m + 1; else hi = m - 1;
    }
    return NULL;
}

#endif // DCT3_TRACE_NAMES_H
